### ISSUE TITLE
Radio/checkboxOne/missing : select the selected modality is considered as a value changed

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#1011]
## Describe the bug

When a radio/checbboxOne/missing has a selected modality, if you select it again (click/shortcut), it considers that the value changed.

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

1. With the survey available here/uploaded in issue
2. Go to '...'
3. Click on '....'
4. See error ...

## Expected behavior

Since the value is still the same, it shouldn't be considered as a value changed

## Version where the bug appeared

3.0.0

## Browser where the bug was tested

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by QRuhier** [comment]
Leads to unexpected behavior in Queen (auto goNext using the changed values)

**Comment by ddecrulle** [comment]
To address this issue, I propose refactoring the Radio component to use the [native input radio](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio). Regarding the checkboxOne component, it's a deprecated component, so I propose to leave it as it is.

For the missing button, you're right, we can add a test before firing the value change.
