### ISSUE TITLE
RondPoint - état de progression dans un rond point

### ISSUE THREAD

**Issue by Grafikart** [InseeFr/Lunatic#1017]
## Feature Description

Pour définir l'état de progression dans un rond point on veut introduire une variable qui permette de sauvegarder l'état. Elle serait dans le JSON et permettrait de sauvegarder la progression au sein de chaque rond point

**Comment by AnneHuSKa** [comment]
@romaintailhurat pour clore cette issue, on mentionne dans Pogues le point pour l'avoir en mémoire ?
