### ISSUE TITLE
Navigation bloquée, variables undefined ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1031]
## Describe the bug

 
VPP ne navigue plus dans son questionnaire, on bloque à une question (pas toujours la même mais quand je le colle dans le storybook, j'ai une erreur page 7 - après avoir répondu Oui à la première, Non à la deuxieme). 

=> I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

Prendre ce json, répondre Oui à la première, Non à la deuxieme. 
[VPP_T.json](https://github.com/user-attachments/files/15757397/VPP_T.json)

## Expected behavior

Une navigation qui fonctionne de nouveau

## Screenshots (Storybook 07/06)
 Lunatic 3.xxx :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/54ffb316-bfb4-4e3a-8e78-fb20e3e0d7fc)

Lunatic 2.xx :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/83d42dc1-1d18-4af3-8604-6de82ac90499)

Lunatic 3. : apparition de undefined ?
![image](https://github.com/InseeFr/Lunatic/assets/71011059/79c4324c-1adc-4942-a53c-3362469aaddc)

## Version where the bug appeared

Version déployée 07/06

## Browser where the bug was tested
 
=> Firefox
 
## Additional context

Souci sur les CheckBoxGroups, tous cochés ?

**Comment by Grafikart** [comment]
Quand je répond "oui" à la première question du JSON je me retrouve à la page 31.3#167, c'est normal ? car ça ne correspond pas à la description du rpoblème :(

**Comment by AnneHuSKa** [comment]
@Grafikart je crois que c'est en fait non à la première puis Oui à la deuxième
