### ISSUE TITLE
Property for CheckBox and Radio for horizontal display

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1037]
## Feature Description

🇬🇧  
Pogues - Eno can be used to specify "QCM" whose answers are booleans ("classic" CheckBoxGroups) or lists of several items. These items are generally of the "scale" type. In this second case, you want to display the modes in horizontal mode.

🇫🇷 
Pogues - Eno permet la spécification des QCM dont les réponses sont des booleens (CheckBoxGroup "classiques") ou des listes de plusieurs modalités. Ces modalités sont en général de type "échelle". On souhaite dans ce second cas afficher les modalités en mode horizontal.

## Use Case

Exemple de présentation cible:
![image](https://github.com/InseeFr/Lunatic/assets/71011059/f20425e3-ec06-495b-9826-a19f5599d9db)

## Proposed Solution

=> orientation="horizontal" for this case, orientation could be "horizontal" and "vertical" (the default behavior).
This props concerns Checkbox (group, one) and Radio.

## Additional Context

https://github.com/InseeFr/Stromae/issues/294
https://github.com/InseeFr/Eno/issues/1031 

## Priority
 High 

## Attachments

If applicable, include any mockups, diagrams, or additional files that help illustrate the feature.

## Related Issues

Are there any existing issues related to this feature request? If yes, please reference them here.

**Comment by ddecrulle** [comment]
Ok for Radio & Checkbox One, need CheckboxGroup

**Comment by AnneHuSKa** [comment]
@Grafikart : je revois cette issue, je ne sais pas si tu l'as en tête ? Merci beaucoup.
