### ISSUE TITLE
Affichage suggester sur plusieurs lignes - contraintes ou possibilités

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1059]
Est-il possible d'afficher le label du suggester sur plusieurs lignes sans dégrader la recherche et l'affichage ?
https://github.com/InseeFr/Lunatic/issues/606

**Comment by Grafikart** [comment]
@AnneHuSKa Possibilité de m'envoyer un JSON d'exemple avec le tableau ?

**Comment by AnneHuSKa** [comment]
@Grafikart : voici un json et la nomenclature associée. 
On ne peut pas encore, en génération "Eno", ajouter les OptionResponses qui permettent d'afficher le label correctement donc, plutôt que de toucher au json sorti d'Eno,  j'ai modifié qq id de la nomenclature pour y faire figurer des libellés un peu longs. Exemple : vente de biens déchets de matières plastiques

[Issue1059.json](https://github.com/user-attachments/files/16261509/Issue1059.json)
[Dechets.json](https://github.com/user-attachments/files/16261510/Dechets.json)

![image](https://github.com/user-attachments/assets/9e8d5f55-d648-4d87-a58f-57acb6e19fce)

merci.
