### ISSUE TITLE
Rond Point - controles

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1069]
## Feature Description

Possibilité d'ajouter un contrôle sur les occurrences.
Exemple RP : 
![image](https://github.com/user-attachments/assets/74722586-1375-4d8a-8f71-a4d3d5076001)

## Use Case
 
Lorsqu'un rond point est utilisé, on peut souhaiter informer le répondant qu'un questionnaire n'est pas terminé lorsqu'il tente de l'envoyer (afin de limiter les questionnaires incomplets).

Cible 1 : un contrôle est fait sur chaque occurrence et affiché sous l'occurrence (exemple : A n'a pas complété son questionnaire, basé sur une condition VTL)
Cible 2 : un contrôle général qui reprend les contrôles des occurrences (exemple : A n'a pas complété son questionnaire, basé sur une condition VTL, B n'a pas complété son questionnaire)

## Proposed Solution
 
If you have a specific solution or implementation in mind, please describe it here. Otherwise, you can leave this section blank.

## Priority
 
- [ ] Medium

**Comment by Grafikart** [comment]
C'est une fonctionnalité particulière qui a été perdue lors du passage à la v3. On a introduit (dans le cas des boucles non paginés le type "ROW". On peut reprendre le principe dans le cas du rond point.

```json
{
	"type": "ROW",
	"criticality": "ERROR",
	"errorMessage": {
		"type": "TXT",
		"value": "Row level : Age doit être > 18"
	},
	"typeOfControl": "FORMAT",
	"control": {
		"type": "VTL",
		"value": "AGES > 18"
	},
	"id": "c1"
},
```

Ce qui donne ça dans le cas de Lunatic.

![image](https://github.com/user-attachments/assets/96d6881f-49fa-4250-8203-776cd2125ff0)

**Comment by AnneHuSKa** [comment]
Ce serait top oui et ca me semble un proxy propre de ce que propose le RP actuellement. S'ils mettent une condition qui décrit les variables qu'ils souhaitent absolument collecter, on pourrait tagguer les incomplets/incorrects donc ca serait très bien.
@BulotF : ca serait propageable en DDI et donc Pogues ?

**Comment by laurentC35** [comment]
row -> occurence

**Comment by BulotF** [comment]
DDI : 
Le rond-point est une séquence à laquelle on peut attacher les contrôles globaux.
Il contient une ou plusieurs boucles qui contiennent chacune une séquence de type loopContent ou filteredloopContent à laquelle on peut attacher les contrôles d'occurrence.

Pogues UI : 
Le rond-point a déjà 2 onglets : Boucle et déclarations.
Rajouter un onglet Contrôle basé sur l'existant.
Comme pour les tableaux dynamiques, proposer de préciser le niveau avec 2 modalités : global / occurrence

Pogues-model : 
- le RoundaboutType est une extension du ComponentType. A ce titre, il est déjà autorisé à avoir des Control.
- depuis les contrôles de tableau dynamique, ControlType dispose d'un scope de type xs:string

Aucune évolution n'est nécessaire pour Pogues-model
