### ISSUE TITLE
Absence de controles dans les boucles non paginées

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1147]
## Describe the bug
Les controles des variables présentes dans les boucles non paginées, décrits dans Pogues et présents dans le json lunatic, ne se déclenchent pas

=> Testé sur le  storybook, confirmation bug Lunatic

## To Reproduce

Utiliser le json joint
 
[Json_Abs_Controles_BouclesNonPaginees.json](https://github.com/user-attachments/files/16818314/Json_Abs_Controles_BouclesNonPaginees.json)

Ne pas saisir de prénom => constater qu'on n'a pas le message "Prénom est vide"

## Expected behavior

Déclenchement des controles
 
 
## Version where the bug appeared

A toujours été présent, mais jamais vu comme crucial. Montée en charge des enquêtes donc besoin qui revient car resignalé.

## Browser where the bug was tested
 
- Firefox

**Comment by QRuhier** [comment]
questionnaire to use : 
- without component 'Question' : [issue_1147_sans_Question.json](https://github.com/user-attachments/files/16906153/issue_1147_sans_Question.json)
- with component 'Question' : [issue_1147_avec_Question.json](https://github.com/user-attachments/files/16906154/issue_1147_avec_Question.json)

**Comment by lailabent** [comment]
Hello,
Le bug semble corrigé sauf que les contrôles ne se déclenchent pas comme il faut.
[json_lunatic_à_tester.json](https://github.com/user-attachments/files/16945894/json_lunatic_a_tester.json)

Par exemple avec ce cas (json lunatic en pj) testé dans le storybook lunatic 3.0 
Si je saisis 3 habitants avec pour prénoms A, vide, B, le contrôle "prénom vaut A" sur l'individu 2 se déclenche à tort.

**Comment by lailabent** [comment]
ça fonctionne parfaitement en réécrivant le contrôle
