### ISSUE TITLE
Declarations are missing in component Dropdown & Suggester

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#1148]
## Describe the bug

When adding declarations on a dropdown component (no matter the type of the declaration), they are not displayed

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

[declaration_dropdown.json](https://github.com/user-attachments/files/16847825/declaration_dropdown.json)

**Comment by JulienCarmona** [comment]
Issue en QF:
![image](https://github.com/user-attachments/assets/21f97a1f-0afc-4a40-87b7-34a5134aa4a3)
![image](https://github.com/user-attachments/assets/9a92a247-e637-4af9-accc-ac47e0f9cf70)

Version fixed sur Lunatic (via Storybook)
![image](https://github.com/user-attachments/assets/6ce23382-622e-445f-a23b-164ea9a6ece5)
![image](https://github.com/user-attachments/assets/d29df14a-1d9b-4a81-9c68-2b861c2c58fe)


C'est ✅ pour moi

**Comment by JulienCarmona** [comment]
@QRuhier ou @AnneHuSKa , pouvez-vous me confirmer que c'est normal que ça fonctionne déjà sur DSFR ? 
![image](https://github.com/user-attachments/assets/427b245a-32fd-469c-8066-ae0eca20c906)
![image](https://github.com/user-attachments/assets/76c1edc0-7b3f-47c0-a171-a201b079627a)

**Comment by QRuhier** [comment]
C'est "normal" : 
- le bug était présent dans le composant de la librairie Lunatic
- le bug n'est pas présent dans le composant de la librairie Lunatic-DSFR
