### ISSUE TITLE
Resizing et conservation ou non des données

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1155]
## Describe the bug

Considérons un THL : 
- on décrit 3 individus
- on saisit les prénoms
- on revient sur la boucle et on saisit 2 individus
=> sur lunatic et Queen, on ne garde que les données du premier
=> sur lunatic DSFR et StromaeDSFR, on garde toutes les données (donc ici les 2 premiers)

 ## To Reproduce

Avec le json joint, saisir 3 individus, saisir des prénoms, passer question suivante, revenir et changer le nb d'habitants
[Json_vidage_oui_non.json](https://github.com/user-attachments/files/17150027/Json_vidage_oui_non.json)

## Expected behavior

Un comportement identique :-)

**Comment by QRuhier** [comment]
@AnneHuSKa Dans tous les cas, en revenant sur le nombre d'invidivus décrivant le nombre d'itération :
- si tu effaces le champ avant de resaisir une valeur, on ne conserve que les données de la 1e itération (puisque dans cette boucle si le nombre d'invidivus n'est pas renseigné la dimension par défaut est 1 donc on clean les autres itérations)
- si tu "sélectionnes" la saisie pour la remplacer (donc sans la remettre à vide), tu gardes toutes les données (dans cet exemple des 2 itérations)

**Comment by AnneHuSKa** [comment]
@QRuhier merci. A noter dans une doc ou à garder en mémoire @lailabent @JulienCarmona
