### ISSUE TITLE
Documenter les composants Duration dans la doc Lunatic

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1156]
## Feature Description

Décrire le composant Durée dans https://inseefr.github.io/Lunatic/docs/category/champs : il est décrit ici https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-duration--date-duration  et https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-duration--time-duration

## Use Case
Proposition : 
"Le composant Duration peut être utilisée pour collecter une date. Elle peut êtré définie en :

    années / mois
    heures / minutes

Les unités figurent en haut des champs de saisie."

Json source :

[Json_duree.json](https://github.com/user-attachments/files/17260740/Json_duree.json)

Expliciter les formats de sortie (pourquoi P ou PT ?) par exemple PT12H50M ET P2000Y4M

## Priority
 
- High (utile pour Traiter)

**Comment by QRuhier** [comment]
Reprise des source.json issus des stories (comme les autres composants)
