### ISSUE TITLE
Infobulles de sous-séquences non affichées sur Storybook => impact poste de reprise ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#1160]
## Describe the bug

L'affichage des infobulles marche parfaitement en Stromae DSFR et Queen mais les infobulles de niveau sous-séquence s'affichent mal quand on utilise le Json sur le poste de reprise Perret.

Cela est peut-être lié à un souci coté Lunatic puisque en lunatic3, les infobulles de sous-séquences ne semblent pas s'afficher ?

Test réalisé : 
- création d'un json Lunatic (en pj)
- viualisation Stromae DSFR : ok
- visualisation Queen : ok
- visualisation Lunatic DSFR : ok

![image](https://github.com/user-attachments/assets/af93bfec-98da-472c-bc9a-8e74bcd7d3be)

- visualisation lunatic 3.0 : ko

![image](https://github.com/user-attachments/assets/5077d7a7-ad11-4710-9228-2312e067ca15)

## To Reproduce

Utiliser le json joint
[Issue1160.json](https://github.com/user-attachments/files/17487426/Issue1160.json)

## Expected behavior

Affichage des infobulles ?

## Browser where the bug was tested
 
 Firefox
 

## Additional context

Utile pour poste de reprise

**Comment by QRuhier** [comment]
Plus généralement : le composant sous-séquence ne lit actuellement pas le champ "description". Les déclarations sont affichées uniquement si c'est lu dans le champ "déclarations" => OK pour génération "non DSFR", KO pour génération "DSFR"

**Comment by AnneHuSKa** [comment]
ok sur storybook
