### ISSUE TITLE
duration component not working in loop

### ISSUE THREAD

**Issue by JulienCarmona** [InseeFr/Lunatic#1169]
### Bug: 
![Image](https://github.com/user-attachments/assets/368be8cd-343f-44a2-b818-5f4a4186e2ed)

- [x] Reproduced on Storybook DSFR and Lunatic

Survey: **m1hw33r1**
Env: **Demo**
Question: **SOMM_ENF1**

### Other
- Don't reproduce from visu directly from Pogues
- bug on this visu https://visualisation-questionnaires-web-v3.demo.insee.io/visualize?source=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fjmoufidi%2FEHIS%2Flunatic-form.json&data=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fjmoufidi%2FEHIS%2Fdata_CAWI_GROUPE1.json&metadata=&nomenclature=%7B%22L_PCS_FEMMES-2-1-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fjmoufidi%2FEHIS%2Fnomenclatures%2FL_PCS_FEMMES-2-1-0.json%22%2C%22L_PCS_HOMMES-2-1-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fjmoufidi%2FEHIS%2Fnomenclatures%2FL_PCS_HOMMES-2-1-0.json%22%2C%22L_ACTIVITES-2-0-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fjmoufidi%2FEHIS%2Fnomenclatures%2FL_ACTIVITES-2-0-0.json%22%7D

**Comment by JulienCarmona** [comment]
Reproduire le bug sur un questionnaire plus petit pour faciliter l'estimation

**Comment by JulienCarmona** [comment]
Je viens de tester un duration sur un questionnaire plus simple. On dirait que ce dernier ne veut pas s'afficher en PE mais est bon en Visu simple.
Survey : m3heig7e ([m3heig7e.json](https://github.com/user-attachments/files/17750023/m3heig7e.json))
Je pense que le lunatic généré pas PE sur DEMO est pas bon
Ex avec un contexte Enreprise, sur les 3 questions 
![{171E8FFE-B38D-4455-A5EF-D3849F52BBD7}](https://github.com/user-attachments/assets/9cc35514-f5a9-4be8-a1a5-85c47d9e9bb2)
il n'y a que la deuxième qui est affichée
![{971B75D9-7EB9-4260-A018-013A1C24038F}](https://github.com/user-attachments/assets/99c86791-6c54-4b7d-a71b-d0b38edb821a)
Les duration n'apparaissent pas

**Comment by AnneHuSKa** [comment]
Qualification : le bug est sur les durées dans les boucles. Cf Json joint 
- une question de type durée hors boucle : tout est ok
- une question de type durée dans les boucles : 
![image](https://github.com/user-attachments/assets/ff6dbdd2-528a-4245-8878-d150c9aa4393)

Json test :
[issue1169.json](https://github.com/user-attachments/files/17750700/issue1169.json)

**Comment by QRuhier** [comment]
Actuellement dans le source.json les variables de duration sont absentes du resizing de la variable définissant la dimension de la boucle.
Aujourd'hui dans Lunatic, les variables de boucle sont initialisées à [], mais lorsque la variable définissant la dimension d'une boucle est modifiée, on resize les variables pour injecter autant de null que la dimension de la boucle
La dimension de la variable duration n'est pas recalculée => contrairement aux autres variables qui deviennent [null, null, ...] , celle-ci reste []

A discuter avec Eno

**Comment by QRuhier** [comment]
- pas de modification dans Lunatic, sera corrigée directement par https://github.com/InseeFr/Eno/issues/1157

**Comment by nsenave** [comment]
Fix dans Eno : 

- https://github.com/InseeFr/Eno/pull/1159

**Comment by JulienCarmona** [comment]
# Validation QF :x:
Je ne sais pas si c'est un pb Eno ou Lunatic mais les deux champs durée de la boucle sont liées...
En tout cas à l'affichage

### [questionnaire](https://conception-questionnaires.recette.insee.fr/questionnaire/m3heig7e)
### Step
1. 2 prenom, aaa et ccc
2. rentre 50 et 2 pour DUREE pour aaa
3. passer la question. BUG on voit déjà un input saisie
4. Saisir 10 et 2 pour DUREE pour ccc.
5. retour arrière. BUG on a modifier la réponse de aaa
6. Telecharger les données: On a bien deux duration diff

Lors de la visu, pour la var DUREE, on garde la même valeur remplie pour toutes les itérations de la boucle.
![{7BE61822-1742-446B-BFF6-19B003314897}](https://github.com/user-attachments/assets/284b1ea0-fb80-4270-9f08-a239b07cfbf5)
![{AF322CAC-F11A-4130-AE50-DC8B2BE49296}](https://github.com/user-attachments/assets/8d461bab-46a1-458d-9fd7-8431455309a9)

Mais les variables collectées sont bien différentes 
[TEST DURATION KO-19_11_2024.json](https://github.com/user-attachments/files/17819222/TEST.DURATION.KO-19_11_2024.json)

**Comment by QRuhier** [comment]
@JulienCarmona Il semble que le problème n'arrive que si la boucle ne contient qu'une seule question duration (ou que les autres sont filtrées) => en gros le fait d'enchainer la duration sur plusieurs itérations

C'est aussi urgent à gérer ?

**Comment by QRuhier** [comment]
@JulienCarmona Bigger issue : c'est le même problème pour un certain nombre de composants (le fait d'enchainer plusieurs itérations sur la même variable)

On n'a pas tout parcouru, mais a minima : 
- duration
- datePicker
- suggester

**Comment by JulienCarmona** [comment]
Ok donc un gros truc quoi. Dans tous les cas je vais donc faire un autre ticket pour ce sujet,

Je repasse ce ticket en Validation pour finir ma recette.
Si tout est bon je passe à Done avec Eno

**Comment by JulienCarmona** [comment]
Si on rajoute un élément, même une autre durée ça marche bien.

Je close ce ticket

**Comment by JulienCarmona** [comment]
Fix dans release 2.4.2 DSFR
