### ISSUE TITLE
Analyse de l'existant "suggester"

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#1172]
## Description

Analyse du fonctionnement des suggesters sur le rendu des echos (liste des echos et ordre d'affichage) sur la 3.0 par rapport à ce qui existait en 2.7

voir doc sur les suggesters https://github.com/InseeFr/Concevoir-Workplace/blob/main/Doc_finalises/Lunatic/Lunatic-2022-notes-suggester.md

### éléments toujours présents

- rend insensible à la casse les echos et la query, retire tous les accents et caractères spéciaux (tiret, slash, cédille...)
- la recherche s'effectue à partir d'une saisie de x caractères  => paramètre "min" (1 par défaut)
- prise en compte des synonymes (exemple : la query "fabrication" match comme s'il s'agissait de "fabricant") => paramètre "synonyms"
- nombre maximum de suggestions présentés à l'utilisateur => paramètre "max" (on renvoie tous les echos qui match par défaut)

### éléments manquants

- stopwords : filtre de la query les mots considérés "stopwords" => liste des stopwords dans le paramètre "stopWords"
  - cf. https://github.com/InseeFr/Lunatic/issues/1161
- stemmer (= lemmatisation) : lemmatise les mots de la query pour tenir compte des echos qui contiennent la racine de ces mots => paramètre "stemmer". cf. demo pour voir le résultat https://snowballstem.org/demo.html#French
  - dans tous nos suggesters on met à false donc on ne l'utilisait pas. Quid du RP ou autres utilisateurs ?
  - pose question dans beaucoup de cas sur la pertinence. Ex je recherche "bâtiment", dans les suggestions je vais trouver "bateau" avant "rénovation de bâtiment"

### éléments toujours présents

- calcul d'un score via algorithme de Meloto pour ordonner les echos
  - ⚠️ il était précédemment appliqué que si le paramètre "meloto" du suggester valait true ou non défini (sinon on renvoyait l'ordre de départ). Désormais il est toujours appliqué

```
/**
 * Melauto scoring algorithm
 *
 * - Rank up result if the word is closer to the start of the string
 * - Rank better the first word in the query
 * - Rank up the proportion of query terms in the string
 */
```

### éléments manquants

- tri pour les echos ayant le même score
  - précédemment il s'agissait d'un tri alpha-numérique
  - cf. https://github.com/InseeFr/Lunatic/issues/1166

**Comment by QRuhier** [comment]
@JulienCarmona @lailabent Je vous propose de regarder l'analyse du fonctionnement actuel (et ce qui a été oublié dans le refacto 2.7->3.0) et faire de nouvelles issues pour les évol que vous souhaiteriez.
Sachant que la partie stopwords aura déjà été corrigée, puisque c'est cette issue qui nous a poussé à faire cette analyse

**Comment by JulienCarmona** [comment]
Au vu de ton analyse, le comportement actuel du suggester nous va bien.

Il ne reste que le tri à implémenter 
- https://github.com/InseeFr/Lunatic/issues/1166

**Comment by JulienCarmona** [comment]
Trace de l'analyse ici : https://github.com/InseeFr/Concevoir-Workplace/blob/main/Doc_courantes/Suggester/Analyse_diff_suggester-Lunatic_2.7_3.0.md
