### ISSUE TITLE
[Perret] - "autre précisez" : toujours l'afficher

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#1179]
## Feature Description

Dans le cas d'utilisation Perret (poste de reprise), les "autre précisez" devraient être affichées dans tous les cas (même si la modalité "autre" n'est pas sélectionnée.

## Use Case
Affichage des questions dans le cas de l'orchestrateur de reprise.

## Proposed Solution

~~Utiliser l'option `management`, si true,  afficher tout le temps les "details" des options dans Lunatic.~~
Rajouter un paramètre dans le useLunatic pour permettre d'afficher tout le temps les modalités "detail".
Dans le cas contraire, avoir le comportement par défaut (affichage conditionné au fait que l'option "autre" ait été sélectionnée)

## Alternatives Considered

Ne pas utiliser Lunatic, car comportement non suchargeable par changement du json Lunatic.

**Comment by QRuhier** [comment]
Attention doit concerner tous les composants permettant l'affichage de detail (CheckboxGroup, Radio, CheckboxOne)

**Comment by QRuhier** [comment]
## Solution conservée
Ajouter un param `detailAlwaysDisplayed` (dans un nouvel objet `componentsOptions`) dans le useLunatic, à false par defaut pour rester compatible avec l'existant.

## Validation
Modification des stories pour les composants concernés avec l'ajout de ce paramètre "detailAlwaysDisplayed" : 
- [checkboxGroup](https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-checkboxgroup--with-detail)
- [checkboxOne](https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-checkboxone--with-detail)
- [radio](https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-radio--with-detail)

Et ajout de ce paramètre "detailAlwaysDisplayed" dans la story ["Paste"](https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/behaviour-paste--default) si l'on souhaite vérifier avec un questionnaire de son choix

**Comment by laurentC35** [comment]
Dispo à partir de la version `3.4.9` de Lunatic
