### ISSUE TITLE
CheckboxOne : cannot be unchecked

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#1189]
## Describe the bug

CheckboxOne is like a radio, but with a checkbox style and should allow to uncheck the checked modality.
Currently it does not allow to uncheck anymore

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

1.Go to a checkboxOne component
2. Check a modality
3. Try to uncheck the modality

## Expected behavior

Modality should be unchecked

## Version where the bug appeared

?

## Browser where the bug was tested

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by QRuhier** [comment]
Even if it's not a standard to make single-choice question modality uncheckable (since it should be radio buttons), we assume that as long as we maintain `CheckboxOne` this components allows to uncheck.

Then `CheckboxOne `works exactly like `Radio`, except : 
- style is changed for looking like checkboxes
- you can uncheck the checked modality

@JulienCarmona @lailabent for the future, do we want to keep this component ?

**Comment by QRuhier** [comment]
For validation :

- checkboxOne : verify you can uncheck
  -  https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-checkboxone--default
- radio : verify you cannot uncheck (no changes)
  - https://inseefr.github.io/Lunatic/storybook-3.0/?path=/story/components-radio--default

**Comment by lailabent** [comment]
Recette ok dans le storybook mentionné
