### ISSUE TITLE
Datepicker : new components ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#141]
To extend the datepicker's format to YYYY or MM/YYYY formats in order to ensure consistent coverage with Pogues

**Comment by romaintailhurat** [comment]
We will have a new component in Lunatic DSFR (implementing [this](https://www.systeme-de-design.gouv.fr/elements-d-interface/blocs-fonctionnels/date-unique)). Should we already implement something close for Stromae V2 ? Is this the same Lunatic DSFR component or something new that will help with the transition ?

**Comment by laurentC35** [comment]
![Image](https://github.com/InseeFr/Lunatic/assets/38245508/cab24a20-7dc5-489d-8e81-1ddf7d107482)

**Comment by laurentC35** [comment]
Is it ComponenSet implementation ? -> nope

**Comment by laurentC35** [comment]
![image](https://github.com/InseeFr/Lunatic/assets/38245508/d4a61d59-3318-4952-a011-6c2900ac5ed4)
