### ISSUE TITLE
Liste déroulante

### ISSUE THREAD

**Issue by philippe-clement** [InseeFr/Lunatic#15]
Bonjour

Actuellement nous ne pouvons pas desactiver les listes déroulantes dans notre orchestrateur pour le cas d'un questionnaire en lecture seule.
Est ce que c'est normale ?

Merci pour vos précisions.

Philippe

**Comment by NicoLaval** [comment]
WIP

**Comment by NicoLaval** [comment]
1f45b25780a0520186173bc3dc32e1fec2120d31
