### ISSUE TITLE
handleChange on dropDown ??? 

### ISSUE THREAD

**Issue by JackLemaitre** [InseeFr/Lunatic#16]
got some issue with the loading of the dropDown component.
the handleChange of the component is used to initialize the value of the dropDown

it would rather not because it triggers the onChange method wich can create a big mess. 
Above all it is not the usual behavior.

**Comment by NicoLaval** [comment]
WIP

**Comment by NicoLaval** [comment]
1f45b25780a0520186173bc3dc32e1fec2120d31
