### ISSUE TITLE
Question Number in case of filter

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#162]
I think that the way of numbering the questions is not appropriate, especially in the case where there are filters.

It is possible to go from question 1 to question 6 if questions 2 to 5 are accessible only if a specific mode is answered in question 1.

This leads to inconsistent numbering in the pagination.

I do not know the perfect way to number question, if it's needed to be dynamic or whatever.

**Comment by NicoLaval** [comment]
You need to have initial pages.
When filtering, we can also build a kind of "live" page number, but this is not efficient, needing a lot of calculation.

The actual way to handle this subject is to only calculate the next or the previous page when clicking on the dedicated button.

**Comment by AnneHuSKa** [comment]
With Eno you can choose an option "no number" if this inconsistent numbering is a real problem. I close the issue
