### ISSUE TITLE
Bug avec la version 1.1.3

### ISSUE THREAD

**Issue by philippe-clement** [InseeFr/Lunatic#18]
Bonjour

Avec la nouvelle version de lunatic , nous avons un souci pour les questions numériques on ne peut pas effacer toute la réponse saisie. 
On a réussi à reproduire ce comportement avec l'orchestrator de demonstration à la question 4. What is the current season number?.

Cordialement,

L'équipe Généric

**Comment by NicoLaval** [comment]
Scheduled to be studied for January 10

**Comment by NicoLaval** [comment]
See #8
