### ISSUE TITLE
For June 2021: Summing a variable in a loop or dynamic array

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Lunatic#185]
For the 2022 Housing Survey Test, the first tests of which are due in June 2021, it is necessary to be able to sum, for example, the number of adults or the number of children over 25 years of age living in the accommodation. This requires being able to sum up, for example, the occurrences of the individual loop of AGE>18 years via the function sum(cast(OLDER18,number)) with OLDER18 defined for each occurrence of the individual loop and a boolean which is worth 1 for individuals more than 18 yeard old and 0 otherwise. We would therefore need the **sum() function** to be functional at the earliest.

**Comment by AnneHuSKa** [comment]
sum ok (since septembre 2021)
