### ISSUE TITLE
For TIC 2022 : implement min() on a dataset

### ISSUE THREAD

**Issue by FabiennePG** [InseeFr/Lunatic#187]
In the TIC survey, the date of birth of each dwelling resident is asked and then the respondent is selected as the one whose birthday is closest to 1 June. We therefore need to retrieve the respondent's day of birth (we already know how to do this), the respondent's month of birth (also OK) and then we can use an if-then-else formula to calculate the number of days between the birthday and 1 June, such as
if isnull(datebirth) then 999
else if monthbirth="01" then 31+28+31+30+31-daybirth
else if monthbirth="02" then 28+31+30+31-daybirth
and so on.
else if monthbirth="06" then daybirth
else if monthbirth="07" then 30+ daybirth
then if monthbirth="08" then 30+31+ daybirth etc.
else 30+31+31+30+31+30+daybirth
then the minimum number of days must be calculated to determine the Kish, so the min must be implemented on a dataset for TIC 2022, unless we find another solution.

**Comment by AnneHuSKa** [comment]
done
