### ISSUE TITLE
New component : "Autres préciser" / "Other" (Checkbox, checkBoxOne)   (11/2022)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#204]
New component : creation of a textual complement to specify the choice of a modality of type "Other" (in checkBox).
 

=> https://github.com/InseeFr/Bowie/issues/5

**Comment by laurentC35** [comment]
Rattrapage fonctionnalités entreprises

**Comment by laurentC35** [comment]
TODO : faire la modélisation Lunatic la plus efficiente

**Comment by AnneHuSKa** [comment]
![image](https://github.com/InseeFr/Lunatic/assets/71011059/383cb661-7225-4b02-8cc3-8db8b4f91ecc)

![image](https://github.com/InseeFr/Lunatic/assets/71011059/4c416356-6058-4d65-a567-bd34e3b6cdb3)

**Comment by AnneHuSKa** [comment]
Validation Lunatic à faire coté Eno (vérifier PR de J)

**Comment by AnneHuSKa** [comment]
@nsenave : si tu peux regarder l'implem stp ?

**Comment by nsenave** [comment]
@AnneHuSKa ~~on discute des détails pour fixer l'implémentation côté Lunatic. Est-ce qu'on a fixé l'implémentation côté DDI ?~~

(je pensais être sur le repo Eno, on discutera de DDI là bas 😇 )

**Comment by QRuhier** [comment]
add the option for radio & checkboxGroup

**Comment by AnneHuSKa** [comment]
@ddecrulle : tu aurais un json exemple stp ? Quand je génère par Eno, le json produit n'a pas la dynamique d'affichage. Merci

**Comment by ddecrulle** [comment]
Il y a que le CheckboxOne qui est implémenté.

Voilà un exemple : 

```json
{
	"$schema": "../../../lunatic-schema.json",
	"components": [
		{
			"id": "checkboxone",
			"componentType": "CheckboxOne",
			"mandatory": false,
			"page": "3",
			"label": {
				"value": "\"checkboxone ONE component\"",
				"type": "VTL|MD"
			},
			"description": {
				"value": "\"true or false\"",
				"type": "VTL|MD"
			},
			"conditionFilter": { "value": "true", "type": "VTL" },
			"options": [
				{
					"value": "1",
					"description": {
						"value": "\"Déclaration oui\"",
						"type": "VTL|MD"
					},
					"label": { "value": "\"oui\"", "type": "VTL|MD" }
				},

				{
					"value": "2",
					"description": {
						"value": "\"Déclaration non\"",
						"type": "VTL|MD"
					},
					"label": { "value": "\"non\"", "type": "VTL|MD" }
				},

				{
					"value": "3",
					"label": { "value": "\"Autre\"", "type": "VTL|MD" },
					"detail": {
						"label": {
							"value": "\"Préciser : \"",
							"type": "VTL"
						},
						"response": {
							"name": "Q3"
						}
					}
				}
			],
			"response": { "name": "Q2" }
		}
	],
	"variables": [
		{
			"variableType": "COLLECTED",
			"name": "Q2",
			"values": {
				"PREVIOUS": null,
				"COLLECTED": null,
				"FORCED": null,
				"EDITED": null,
				"INPUTED": null
			}
		},
		{
			"variableType": "COLLECTED",
			"name": "Q3",
			"values": {
				"PREVIOUS": null,
				"COLLECTED": null,
				"FORCED": null,
				"EDITED": null,
				"INPUTED": null
			}
		}
	]
}
```

**Comment by ddecrulle** [comment]
@romaintailhurat @AnneHuSKa  Vous me confirmez que cette option arbitraire est souhaitée pour le composant `CheckboxGroup` et `Radio` ? 

Pour le Radio c'est très similaire au CheckboxOne, pour le CheckboxGroup c'est différent car chaque option correspond à une variable. Il faudrait donc créer une nouvelle variable. On doit se mettre d'accord avec @nsenave sur le model dans ce cas. 

Une proposition pourrait être : 
```json

{
    "componentType": "CheckboxGroup",
    ...
    "responses": [
        {
            "id": "opt-arbitrary",
            "label": {
                "value": "\"Option Arbitraire\"",
                "type": "VTL|MD"
            },
            "response": { "name": "Q_ARBITRARY" },
            "detail": {
                "label": {
                    "value": "\"Préciser : \"",
                    "type": "VTL"
                },
                "response": {
                    "name": "Q_ARBITRARY_DETAIL"
                }
            }
        }
    ]
}
```

**Comment by romaintailhurat** [comment]
Pas d'idée sur le modèle précis mais oui, je confirme qu'il faudrait pouvoir disposer de ce composant sur Radio et CheckBoxGroup et donc ok pour avoir une nouvelle variable dans ce cas (nommée `<QuestionName>_ARBITRARY` si j'ai bien compris).

**Comment by nsenave** [comment]
Oui c'est logique qu'il faille une variable supplémentaire pour chaque "arbitrary" dans le cas d'un checkbox group.

De façon provisoire on pourra générer ces variables supplémentaires dans Eno au moment de la génération du json Luantic, par exemple avec ce que tu proposes @romaintailhurat  `<nom de la variable associée à la modalité>_ARBITRARY`.

Mais il faudra à terme que cette info soit définie dans Pogues (pour qu'on ait aussi ces variables dans le DDI notamment).

En tout cas ok avec ce choix côté Lunatic 👍
