### ISSUE TITLE
Controles - comportement des controles de cohérence

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#205]
Controles non bloquants  à ce stade

**Demande : ne pas déclencher le controle à l'entrée sur la page si possible**

___________________________________________________________________________________________________________
Mémo à tester  
* customisation of error labels 
* Regular expression controls (Pogues)

**Comment by ORogel** [comment]
https://hackmd.io/NDLtN6h1RcCFwu3aMh7tUw?edit
