### ISSUE TITLE
"Loops of loops" - Nested Loop - Boucle de boucles (Use case Famille)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#214]
🇬🇧
Example : describe for each person in the household, the savings accounts and describe these accounts (HVP)

🇫🇷 
Proposer des boucles de boucles :
-    on boucle sur des individus, et pour chaque individu, on boucle sur ses enfants puis sur ses parents (UseCase : enquête famille)
 -   on boucle sur des individus et pour chacun on liste les livrets d’épargne et on décrit ces livrets (et baser la boucle de description des livrets sur une boucles ad-hoc pour donner une dénomination à chaque livret).

[Document de cadrage](https://hackmd.io/K8xb8wzURyuoHF7S9D9rvw)

https://github.com/InseeFr/Pogues/issues/548

**Comment by ORogel** [comment]
@AnneHuSKa & @romaintailhurat : pouvez-vous préciser la navigation pour le répondant dans le cas d'une boucle de boucle ? Est-elle linéaire ? Y-a-t-il un système de "rond-point" ?

**Comment by AnneHuSKa** [comment]
Romain avait proposé un petit schéma que je ne retrouve pas mais à mon sens on doit pouvoir proposer le rond point sur la première boucle, MAIS pas sur la seconde.
a. je ne pense pas que ca réponde à un besoin (exemple ci dessous)
b. trop de rond points en cascade cassent la navigation du questionnaire et donc sa compréhension par l'enquêté.

Cas usage Famille : on collecte les infos pour n individus, l'ordre de remplissage des n individus est aujourd'hui "imposé", mais on voudrait offrir le choix (donc proposer un rond point). On peut par exemple imaginer que l'individu A n'est pas présent donc que B commence à remplir le questionnaire. Pour chaque individu, on va ensuite poser pas mal de questions dont une sous-séquence sur ses enfants. Le nb d'enfants - taille de la boucle - est saisi par le répondant qui ensuite remplit chaque "sous-séquence enfant" : B remplit le questionnaire, il choisit l'ordre dans lequel il saisit les prénoms des enfants et ensuite, remplira dans l'ordre de la saisie. Ca me semble être un usage différent, donc sans rond-point.

Question bonus : les boucles principales sont aujourd'hui sur une page unique. Pourquoi ? exemple : on a 4 individus, on affiche 4 fois la sous-séquence "Prénom des invididus" et 4 fois la question.  Il ne faudrait pas avoir ce comportement sur la boucle de boucles, mais bien garder du "une question par page" (la boucle de boucle n'a été identifiée que pour des besoins ménages).

**Comment by ORogel** [comment]
OK. Et a-t-on besoin de résumé d'info au niveau de la 2ème boucle (du genre "rappel Parent XXX" ou "rappel Enfant AAA") ? 
Réponse d'Anne : "A mon sens il faut qu'on puisse récupérer l'information si on a besoin de la valoriser (comme aujourd'hui quand on dit "quel est l'état civil de Gérard Bouchard" dans une boucle simple) : donc être capable d'avoir d'afficher un truc comme cela :"
![image](https://user-images.githubusercontent.com/59668260/220416749-84e489a9-e968-4a72-a778-467a929548bc.png)
source : spec Famille dans Pogues 
Ils ont des 1 car ils ont créé 16 occurrences...
