### ISSUE TITLE
Filter the options or responses of a "CheckboxGroup" or "CheckboxOne" 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#225]
Filter with the answers to previous questions

**Comment by romaintailhurat** [comment]
@romaintailhurat to produce specs

**Comment by AnneHuSKa** [comment]
@romaintailhurat et @AnneHuSKa : refaire spec

**Comment by AnneHuSKa** [comment]
On peut souhaiter personnaliser les modalités de réponses proposées à une question en fonction du profil ou des réponses à des questions précédentes.

**Exemple** :
Quel est votre situation ?
- étudiant 
- chomeur
- actif
- retraité
Si la personne a moins de 18 ans, on peut ne pas vouloir proposer retraité

**ou dans l'exemple ci-dessous**, on souhaite afficher certaines modalités si la personne est concernée : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/c1fdb915-0a6a-44ae-9426-b960c3f166c9)

Aujourd'hui, le contournement est de mettre un filtre sur la modalité mais elle reste affichée.

Idéalement, on souhaiterait : 
- que la modalité ne soit pas affichée
- que les modalités de réponse soient inchangées.

**Comment by laurentC35** [comment]
Modélisation : `conditionFilter` adossé à chacune des options

**Comment by AnneHuSKa** [comment]
@QRuhier https://github.com/InseeFr/Lunatic/pull/1071 : ok en Lunatic donc ?

**Comment by QRuhier** [comment]
@AnneHuSKa Oui depuis lunatic 3.4.0

**Comment by JulienCarmona** [comment]
Test avec filtre sur l'age 
```json
"conditionFilter": {
	"value": "nvl(AGE, 0) > 18",
	"type": "VTL"
}
```
Radio button ("checkboxOne") : ✅ 
![image](https://github.com/user-attachments/assets/164e3837-ac10-4fc2-b7b3-f51ae1db30ca) ![image](https://github.com/user-attachments/assets/a81d5718-1925-455e-b8dd-4711c5cdfcb4)

checkboxGroup : ✅ 
![image](https://github.com/user-attachments/assets/b349b723-9202-4b39-8168-d28e959b65db) ![image](https://github.com/user-attachments/assets/458a51d6-ac4f-46cf-8689-c87f759fe42c)

**Comment by JulienCarmona** [comment]
Test fait avec un exemple plus complet : [sourceCondition_radio.json](https://github.com/user-attachments/files/16872143/sourceCondition_radio.json)
On affiche certaines modalites de la Q2 suivant la selection de Q1
![image](https://github.com/user-attachments/assets/f7636753-5977-4351-951e-4e201ff3732c)
![image](https://github.com/user-attachments/assets/3ce4537a-8a26-45d5-a19f-23bde29438ba)
