### ISSUE TITLE
Bug : rosterForLoop, loop built on it // ko when pagination = sequence

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#230]
rosterForLoop -> loop built on it 

Pagination = sequence
-> all on the same page, we are stuck on this page
https://stromae-v2-sandbox.dev.insee.io/visualize?questionnaire=https://minio.lab.sspcloud.fr/ahusseini/tableau_boucleliee_decoupParSequence.json

Pagination = question
-> several pages, ok
https://stromae-v2-sandbox.dev.insee.io/visualize?questionnaire=https://minio.lab.sspcloud.fr/ahusseini/tableau_boucleliee_decoupParQuestion.json

This bug exists in Stromae : 2.1.70 | Lunatic : 0.3.9-experimental but not in Stromae : 2.1.51 | Lunatic : 0.3.5-experimental

* rosterForLoop -> boucle qui s'appuie dessus -> le tout sur la même page, on est bloqué sur cette page*

**Comment by MickaelMenet** [comment]
seems to be ok
