### ISSUE TITLE
CheckBox and Suggester - how to get the Label ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#236]
Use case : to use the label in a statement or in another question
"Dans votre profession de ****, êtes vous amené à etc."

OU

Afficher le label et non l'identifiant dans le cas d'un dropdown ou d'un suggester.

**Comment by romaintailhurat** [comment]
@AnneHuSKa to produce specs

**Comment by AnneHuSKa** [comment]
Prenons l'exemple suivant : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/054d9eb4-0539-4e39-b3c8-16071e28d8af)
On voudrait ensuite poser la question telle que : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/967d5fd9-261e-4d3f-ab96-a4695f819ffa)
donc récupérer le label associé à la value de la réponse précédente.


Json actuel : 
[Lunatic236.json](https://github.com/InseeFr/Lunatic/files/15198663/Lunatic236.json)


Si cout élevé, on abandonne

**Comment by ddecrulle** [comment]
Il faut trouver la bonne expression VTL (si cela est possible), je me permets de clore l'issue, ce n'est pas de la responsabilité de Lunatic.
