### ISSUE TITLE
FilterDescription - how to manage it in "Filter" mode ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#241]
When the description (in Pogues) is made in "filter" mode, the FilterDescription  is missing. We tried to add these FilterDescriptions in "filter" mode, except that their presence seems to interfere with web browsing (and CAPI browsing).
Example : https://questionnaire-particuliers.recette.insee.fr/visualize?questionnaire=https://minio.lab.sspcloud.fr/ahusseini/Filtre_QF2paramFilterDescFalse.json : if you check No to Q1, you should go to Q3 but there, you have first a blank page.

**Comment by MickaelMenet** [comment]
The questionnaire is no longer available on the url.

**Comment by AnneHuSKa** [comment]
I put it back, sorry.

you can also compare jsonQF2_filtre_descfalse.json and jsonQF2_redir_descFALSE.json  : with "redirection", no pb but with "filter" (when Q1 = 2 - https://questionnaire-particuliers.recette.insee.fr/visualize?questionnaire=https://minio.lab.sspcloud.fr/ahusseini/jsonQF2_filtre_descfalse.json)

This pb is on Lunatic V1 (with the Eno whiche generates Lunatic V1) but I think it will be the same for LunaticV2. No emergency but...
