### ISSUE TITLE
Duration : 2 composants

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#258]
Mise à jour mars 2024 :
2 composants  uniquement dans Lunatic :
PTnHnM --> format heures/minutes (min PT0H0M:, max PT99H59M)
PnYnM --> années/mois (min : P0Y0M, max : P9999Y11M) 

Mémo Pogues : supprimer HHCC

**Comment by AnneHuSKa** [comment]
[ddi_duration_proposées_Pogues.zip](https://github.com/InseeFr/Lunatic/files/9239928/ddi_duration_proposees_Pogues.zip)

**Comment by AnneHuSKa** [comment]
DDi and XML Pogues for Duration

**Comment by ORogel** [comment]
![image](https://user-images.githubusercontent.com/59668260/183427581-e3a56775-719c-4b87-b30c-1ea6884cd356.png)

**Comment by ORogel** [comment]
PTnHnM --> format heures/minutes (min PT0H0M:, max PT99H59M) 
PnYnM --> années/mois (min : P0Y0M, max : P99Y11M)
1 unique variable derrière : sur le format des min et des max

**Comment by ORogel** [comment]
{
      "id": "j6q9h8tj",
      "componentType": "Duration",
      "mandatory": true,
      "page": "5",
      "min": "PT0H0M",
      "max": "PT99H59M",
      "format": "PTnHnM",
      "label": "\"➡ 4. Combien de temps avez-vous mis à répondre à ce questionnaire ?\"",
      "conditionFilter": {
        "value": "(not(cast(READY,integer)  <>  1))",
        "bindingDependencies": [
          "READY"
        ]
      }
     
     
     
         {
      "id": "j6q9h8tj",
      "componentType": "InputNumber",
      "mandatory": true,
      "page": "5",
      "min": 0,
      "max": 99,
      "decimals": 0,
      "label": "\"➡ 4. What is the current season number?\"",
      "conditionFilter": {
        "value": "(not(cast(READY,integer)  <>  1))",
        "bindingDependencies": [
          "READY"
        ]
      }

**Comment by laurentC35** [comment]
ToDo : ComponentSet !!!!!!!
-> NON, car une seule réponse

**Comment by laurentC35** [comment]
![image](https://github.com/InseeFr/Lunatic/assets/38245508/bf135a00-7959-411e-b25a-bdd8f8145fec)


type Formats = "PTnHnM" | "PnYnM";

**Comment by laurentC35** [comment]
ToDo: ajouter le format de durée dans la sortie lunatic d'Eno
