### ISSUE TITLE
controle input number

### ISSUE THREAD

**Issue by philippe-clement** [InseeFr/Lunatic#27]
Dans POGUES on a saisi un controle sur un nombre entier inférieur à 100
Si on rentre un nombre non entier avec virgule, il n'y a pas d'indication que le nombre n'est pas valide.
Est ce corrigeable ?

**Comment by NicoLaval** [comment]
Seems to be good with the InputNumber Lunatic component: https://inseefr.github.io/Lunatic/storybook/?path=/story/inputnumber--props
