### ISSUE TITLE
[V2] <label /> without input field

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#274]
In my opinion there is no reason to use a html [`<label>`](https://developer.mozilla.org/fr/docs/Web/HTML/Element/Label) without input field and to not use <label> in input with text.

* Component without Input which uses label : 
    - [x] [Sequence](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/sequence/sequence.js#L14) 
    - [ ] [LunaticComponent](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/commons/components/lunatic-component.js#L32)
    - [ ] [Radio Group](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/radio/radio-group.js#L16)
    - [ ] [CheckBox Group](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/checkbox/checkbox-group/checkbox-group.js)

* Component with input which doest not uses `<label>` :  All input components (use `<span>` today)

**Comment by AnneHuSKa** [comment]
Issue : still available ?

**Comment by AnneHuSKa** [comment]
Can we close this issue ?
