### ISSUE TITLE
[V2] Things that cause many rerender

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#279]
There is few things that need to be memoize callback or whatever to avoid many rerender. 

This is a non exhaustive list : 

- [ ] `logFunction` :  this may caused by [this code](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/commons/components/md-label/md-label.js#L17)
- In Radio, LunaticRadioGroup, InputNumber ... 
    *  [ ] `hierarchy`
    * [ ] `missingResponse`
    * [ ] `options`
    * [ ] `declarations`
    * [ ] `value`
    * [ ] `onChange`
- Fieldset
    * [ ] `children`
  
- OverlayField
    * [ ] `controls`

**Comment by AnneHuSKa** [comment]
On a toujours le souci ?
