### ISSUE TITLE
[V2] Vtl expression cause error 

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#280]
This error ocured many times.

![image](https://user-images.githubusercontent.com/81740200/178756082-5a865be2-9639-4ccf-a3df-4436788445b6.png)

For instance with this [survey](https://minio.lab.sspcloud.fr/ddecrulle/questionnaires/V2_boucles_jsonweb_question.json) after entering the first names. 

I think issue is deeply linked with this [questionnaire](https://minio.lab.sspcloud.fr/ddecrulle/questionnaires/V2_boucles_jsonweb_sequence.json), (the same but display by sequence)

**Comment by AnneHuSKa** [comment]
Other example : https://minio.lab.sspcloud.fr/ahusseini/V2_BoucleSequence_filtrees.json (bug for the second question) which is a label with VTL

**Comment by ORogel** [comment]
Closed with this commit : https://github.com/InseeFr/Eno/commit/6c210c5c515339557ff96b2af6c71b58b4b4560b
