### ISSUE TITLE
[V2] Declaration : props not passed

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#282]
[`Declarations`](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/declarations/declarations.js) components do not receive the correct props. 

As you can see [here](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/sequence/sequence.js#L16) there are only the props `declarations` which is passed so id is undefined and is rendered as :

```html 
<div
	id="declarations-undefined-AFTER_QUESTION_TEXT"
	class="lunatic-declarations"
>
	<div class="declaration-lunatic declaration-instruction">
		<p style="margin: 0px;">THE STRING IN declarations</p>
	</div>
</div>;
```

I checked and `id` is never passed to `Declaration` component (not only in Sequence component).

**Comment by MickaelMenet** [comment]
done
