### ISSUE TITLE
[V2] CheckBoxOne and radio : same behaviour ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#286]
I think that the CheckBoxOne component has the same behaviour as the Radio component : we can't cancel the selected choice.

[V2_CheckBoxOne_Radio.zip](https://github.com/InseeFr/Lunatic/files/9142353/V2_CheckBoxOne_Radio.zip)

**Comment by MickaelMenet** [comment]
Done
