### ISSUE TITLE
Pairwise (first version)

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic#299]
- [x] check if xAxis & yAxis are really calculated into state
- [x] conditionFilter
- [ ] pagination
- [ ] Pairwise block model

**Comment by AnneHuSKa** [comment]
UC : to describe all the types of relation between the people of a household

Previous issue : https://github.com/InseeFr/Lunatic/issues/203

**Comment by AnneHuSKa** [comment]
En production le 14 juin
