### ISSUE TITLE
Disabled in table

### ISSUE THREAD

**Issue by philippe-clement** [InseeFr/Lunatic#3]
It seems that we couldn't disable (or readonly) a component when the component is in a table.

are we noobs ?

**Comment by NicoLaval** [comment]
What's the use case ?

We can easily add `disabled` and `readOnly` props to the `Table` component and provide them to children ones. All cells would then be affected, and it's seems to be a brutal (but low cost) solution.

To be more realistic, we can imagine that components are disabled or not according to te the linked variable. `Table` `cells` props are array of components, which have the responsabilty to carry the information into its own props. If the status has to evolve according to variable updates, you have to run through the questionnaire and handle `disabled` or `readOnly` values.
