### ISSUE TITLE
Breadcrumb component

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic#300]
For Queen

**Comment by AnneHuSKa** [comment]
**Fil d'Ariane** 

**Affichage de > Titre de séquence** 
Si on est dans une séquence hors sous-séquence, possibilité de revenir au début de la séquence en cliquant sur le nom de la séquence (cliquable, souligné)
Titre de la séquence souligné


**Affichage de > Titre de séquence > Titre de sous séquence**
Si on est dans une sous-séquence, possibilité de revenir au début de la sous-séquence en cliquant sur le nom de la sous-séquence (cliquable, souligné)
Si on est dans une sous-séquence, possibilité de revenir au début de la séquence en cliquant sur le nom de la séquence (cliquable, non souligné)
Titre de la sous-séquence souligné

Changement de séquence :  https://github.com/InseeFr/Queen/issues/194

Polices : majuscules
