### ISSUE TITLE
a `goLastReachedPage` to be directly redirected to the first unreached page

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic#302]
* What means a the last reached page ? 
       - the first unanswered question or the last question already viewed 
       - what do we want in our surveys?

**Comment by AnneHuSKa** [comment]
Still an issue ?

**Comment by SimonDmz** [comment]
Still needed for Queen, VTL filtering should be handled by Lunatic
workaround until the feature  : goNextPage until no COLLECTED data ?

**Comment by romaintailhurat** [comment]
Need to check and measure the complexity of this feature

**Comment by romaintailhurat** [comment]
@MickaelMenet @laurentC35 En causer à Jonathan pour le mettre sur le sujet

**Comment by MickaelMenet** [comment]
Une branche de Jonathan à ce sujet voir pour tester : https://github.com/InseeFr/Lunatic/pull/567/files

**Comment by romaintailhurat** [comment]
Tester avec le questionnaire Famille sur https://gotopage.demo.insee.io/visualize

**Comment by laurentC35** [comment]
duplicated with #657
