### ISSUE TITLE
Feedback V2 : page 36 of Logement

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic#303]
: "Nous allons vous interroger sur if (isnull(NBHAB)) then "le statut d'occupation de votre ménage" else (if (cast(NBHAB,integer)=1) then "votre statut d'occupation" else (if (not(isnull(nbpersmaj)) and cast(nbpersmaj,integer)>1) then "le statut d'occupation de votre ménage, les statuts d'occupation individuels des occupants du logement" else "le statut d'occupation de votre ménage" ) ) et la date d’installation dans le logement."

**Comment by AnneHuSKa** [comment]
nbpersmaj : calcul avec les données de boucle donc tant que boucles ko, formule ko
