### ISSUE TITLE
Feedback V2 :  Simpson - question 20

### ISSUE THREAD

**Issue by ORogel** [InseeFr/Lunatic#304]
"Minified React error https://github.com/InseeFr/Lunatic/issues/31; visit [https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvalue%2C%20type%7D](https://reactjs.org/docs/error-decoder.html?invariant=31&args%5B%5D=object%20with%20keys%20%7Bvalue%2C%20type%7D) for the full message or use the non-minified dev environment for full errors and additional helpful warnings." Maybe it is a table ?

**Comment by AnneHuSKa** [comment]
Solved
