### ISSUE TITLE
Controles - comportement des controles de format

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#313]
* pour le Input, bloquer au nb maximum de caractères possibles : ok !

* Pour InputNumber, on a 3 messages liés au format, qui se déduisent de la description Pogues et avec un libellé personnalisé :
	un sur le format Nombre, 
	un sur les bornes, 
	un sur les décimales
**si vide ou null  on n'affiche pas de controles de format**

* si nombre de décimales trop élevé, le message est « Le nombre doit comporter au maximum 0 chiffre(s) après la virgule. » : ok !

* Si controle de format : bloquant

**Comment by ddecrulle** [comment]
Normalement les contrôles sont affichés que si l'on est entré dans la case ou que l'on a déjà était sur la page et fait un next ou previous
