### ISSUE TITLE
Lunatic - boucles - pb de calcul des variables dans les boucles

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#314]
Les variables des boucles ne semblent plus se calculer :
https://questionnaire-particuliers.recette.insee.fr/visualize?questionnaire=https%3A%2F%2Fminio.lab.sspcloud.fr%2Fahusseini%2Fform.json
https://stromae-lunatic-v2.dev.insee.io/visualize?questionnaire=https%3A%2F%2Fpogues-back-office-sandbox.dev.insee.io%2Fapi%2Fpersistence%2Fquestionnaire%2Fjson-lunatic%2Fkt32raif

**Comment by ddecrulle** [comment]
Ok bug identifié en faite c'est qu'au moment ou l'on affiche les variables, le calcul n'a pas encore été exécuté. Pour preuve faire retour puis next et hop le résultat s'affiche.

**Comment by AnneHuSKa** [comment]
Je vais regarder tout à l'heure mais ce que je voyais : si on collecte une variable dans  une boucle (AGE), qu'on calcule une indicatrice (IND_MAJEUR par exemple), cette indicatrice prend toujours la même valeur (celle qu'on calcule avec la dernière saisie de AGE).
La "portée" (concept Pogues) qui permet de dire si la variable calculée repose sur des données d'une boucle ou d'un questionnaire ne semble pas valoriser.

Je revérifie

**Comment by ddecrulle** [comment]
Un rapide fix pour les variables calculées. Il y a le même problème pour les variable collectées dans les boucles.

**Comment by AnneHuSKa** [comment]
@ddecrulle tu sais s'il y a une nouvelle version pour que je recette des questionnaires un peu plus de questionnaires complexes ? Logement par exemple
