### ISSUE TITLE
Lunatic - boucles -  les boucles de 1 à n ne semblent pas fonctionner

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#315]
https://stromae-lunatic-v2.dev.insee.io/visualize?questionnaire=https%3A%2F%2Fpogues-back-office-sandbox.dev.insee.io%2Fapi%2Fpersistence%2Fquestionnaire%2Fjson-lunatic%2Fkx0a2hn8

**Comment by ddecrulle** [comment]
This is not a lunatic bug. The survey should provide `RosterForLoop` component instead of `Loop`.
