### ISSUE TITLE
Saisie de texte dans InputNumber - revoir le comportement si possible

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#316]
Saisie de texte dans InputNumber : possible mais non enregistré au changement de page c’est ca ? Peut-on bloquer la saisie ?

**Comment by ddecrulle** [comment]
Effectivement, c'est possible mais la valeur n'est pas sauvegardée

**Comment by AnneHuSKa** [comment]
Could be solved with mui
