### ISSUE TITLE
Saisie en numérique du . 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#317]
Saisie en numérique du . (pavé numérique notamment) : efface la zone (firefox ?)

**Comment by AnneHuSKa** [comment]
yes !

**Comment by AnneHuSKa** [comment]
Je réouvre car j'ai l'impression que ca ne marche plus (en stromaeV2 car en storybook c'est ok)

**Comment by MickaelMenet** [comment]
Déployé dans la version lunatic [2.0.6-v2] non présente encore sur stromae

**Comment by AnneHuSKa** [comment]
ok (Stromae 2.2.12)
