### ISSUE TITLE
Modal - libellé affichage des boutons

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#323]
Ajout de typeOfcontrol pour pointer les controles de format.
typeOfcontrol : FORMAT, "post_collecte", Consistency (et pour Consistency : criticity)

Si typeOfcontrol à FORMAT alors :
- titre de la modal = Erreur bloquante
- un bouton unique : Corriger ma réponse 
   => si clic sur corriger, retour sur la page en cours
- visuel : proche de StromaeV1 OU a minima proche de Stromae V2-Lunatic V2

Si typeOfcontrol à Consistency / Criticité à ERROR, WARN, INFO alors :
- titre de la modal = Avertissement
- deux boutons : Corriger ma réponse // Poursuivre 
       =>si clic sur corriger, retour sur la page en cours, si clic sur Poursuivre non passer à la page suivante
- visuel : proche de StromaeV1 OU a minima proche de Stromae V2-Lunatic V2

**Comment by ddecrulle** [comment]
The label title must be included in the survey file. Lunatic is a library used in several other apps. We don't want to be specific but generic. We don't want to hard code in the lib such things

**Comment by AnneHuSKa** [comment]
ok but with StromaeV2, we have to use "French" terms. So it is maybe in Stromae ?

**Comment by ddecrulle** [comment]
It's a solution, modal title are not supposed to be shared with other client like Prisme, Genric, Queen ? I not very agree with, but why not

**Comment by AnneHuSKa** [comment]
=> C'est à l'orchestrateur de porter

**Comment by AnneHuSKa** [comment]
Si un bouton unique Correct devient : "Corriger ma réponse" 
Si 2 boutons Correct et Ignore devient ; "Corriger ma réponse // Poursuivre"

**Comment by MickaelMenet** [comment]
Déployé dans la version lunatic [2.0.6-v2] non présente encore sur stromae

**Comment by AnneHuSKa** [comment]
ok (Stromae 2.2.12)

**Comment by romaintailhurat** [comment]
Released with https://github.com/InseeFr/Bowie/releases/tag/1.0.0
