### ISSUE TITLE
Unité - pas d'affichage de l'unité

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#326]
https://pogues-sandbox.dev.insee.io/questionnaire/l7qakpbc

**Comment by ddecrulle** [comment]
I just need to know if there is a `unitPosition` I don't see the props in the survey but in the v1 implementation

**Comment by ddecrulle** [comment]
I added a story to easy see what happens [here](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/ccomponents-inputnumber--unit-euros), the style isn't perfect but need spec to improve it (or wait [lunatic-mui](https://github.com/ddecrulle/lunatic-mui/))

**Comment by AnneHuSKa** [comment]
lunatic-mui and maybe a bit of "painting" if possible for Stromae. No emergency
