### ISSUE TITLE
Controles - absence de controles boucle paginée

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#330]
UC : collecter un nb d'individus, collecter les n prénoms : le controle sur le prénom (présent dans json) ne s'affiche pas 
https://pogues-sandbox.dev.insee.io/questionnaire/l7t51pzu

Testé en LunaticV2 : ko

**Comment by Grafikart** [comment]
See https://github.com/InseeFr/Lunatic/issues/409
