### ISSUE TITLE
Booleen - ajout d'un libellé à tort

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#356]
Le format de réponse booleen ne doit pas reprendre le libellé de la question (apparu en octobre 2022) : https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/components-checkboolean--default

**Comment by ddecrulle** [comment]
Je m'occupe de ça, j'en profite pour refondre le composant checkbox et pour le rendre accessible

**Comment by MickaelMenet** [comment]
https://github.com/InseeFr/Lunatic/pull/412
