### ISSUE TITLE
Pairwise : Label adjustment

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#358]
https://github.com/InseeFr/Lunatic/blob/v2-develop/src/stories/pairwise/links.json
For "componentType": "PairwiseLinks"**

- [x] Today "label": {
						"value": "\"Quel est le lien entre \" || xAxis || \" et \" || yAxis || \" ?\"",
						"type": "VTL|MD"
					},

To be changed in  
 "label": {
						"value": "\"Qui est \" || yAxis || \" pour \" || xAxis || \" ?\"",
						"type": "VTL|MD"
					},

**Label is changed AND the order of xAxis  and yAxis**

*Example*
Pour un logement composé de cinq personnes : Anna, Bruno, Charles, Danielle, Eva 
Qui est Bruno pour Anna ?
Qui est Charles pour Anna ?
Qui est Danièle pour Anna ?
Qui est Eva pour Anna ?
Qui est Anna pour Bruno ?
Qui est Charles pour Bruno ?

Etc… ?

---------------------------------------------------------------------------------------
*Expected question*
Début du module de déclaration de la structure familiale
Boucle sur les prénoms des habitants
Anna : Quel est le lien d’Anna avec les habitants du logement situé à l’adresse ADR ?
	Bruno est le ____________ de Anna
	Charles est le ____________ de Anna
	Danielle est la ____________ de Anna
	Eva est la ____________ de Anna
Bruno : Quel est le lien de Bruno avec les habitants du logement situé à l’adresse ADR ?
	Charles est le ____________ de Bruno
	Danielle est la ____________ de Bruno
	Eva est la ____________ de Bruno

- [ ] "options" have to be changed in 

                                                         { "value": "1", "label": "\"Sa conjointe, son conjoint\"" },
                                                         { "value": "2", "label": "\"Sa mère, son père\"" },
                                                         { "value": "3", "label": "\"Sa fille, son fils\"" },
                                                         { "value": "4", "label": "\"Sa belle-mère, son beau-père, le conjoint du parent\""},
                                                         { "value": "5", "label": "\"Sa belle-mère, son beau-père, le parent du conjoint\""},
                                                         { "value": "6", "label": "\"L’enfant du conjoint\"" },
                                                         { "value": "7", "label": "\"Le conjoint d’un enfant\"" },
                                                         {"value": "8", "label": "\"Sa sœur, son frère (y compris demi et quasi)\"" },          
                                                         { "value": "9", "label": "\"Son grand-parent\"" },
                                                         { "value": "10", "label": "\"Son petit-enfant\"" },
                                                         { "value": "11", "label": "\"Sa tante, son oncle\"" },
                                                         { "value": "12", "label": "\"Sa cousine, son cousin\"" },
                                                         { "value": "13", "label": "\"Sa nièce, son neveu\"" },
                                                         { "value": "14", "label": "\"Sa belle-sœur, son beau-frère, (sœur ou frère du conjoint)\"" },
                                                         { "value": "15", "label": "\"Un enfant placé\"" },
                                                         { "value": "16", "label": "\"Autre\"" }

**Comment by ddecrulle** [comment]
Hey, 

Do these changes to the options affect the links?

**Comment by AnneHuSKa** [comment]
Update :
{ "value": "1", "label": "\"Son conjoint, sa conjointe\"" },
{ "value": "2", "label": "\"Sa mère, son père\"" },
{ "value": "3", "label": "\"Sa fille, son fils\"" },
{ "value": "4", "label": "\"Sa soeur, son frère (y compris demi et quasi)\""},
{ "value": "5", "label": "\"Sa belle-mère, son beau-père (conjoint.e d'un des parents)\""},
{ "value": "6", "label": "\"L'enfant du conjoint (belle-fille, beau-fils)\""},
{ "value": "7", "label": "\"Sa belle-mère, son beau-père (parent du conjoint)\""},
{ "value": "8", "label": "\"Sa belle-fille, son beau-fils (conjoint.e d'un enfant)\""},
{ "value": "9", "label": "\"Sa grand-mère, son grand-père\""},
{ "value": "10","label": "\"Sa petite-fille, petit-fils\""
{ "value": "11","label": "\"Sa tante, son oncle\""},
{ "value": "12","label": "\"Sa cousine, son cousin\""},
{ "value": "13","label": "\"Sa nièce, son neveu\""},
{ "value": "14", "label": "\"Un enfant placé en famille d'accueil\"" },
{ "value": "15", "label": "\"Sa belle-soeur, son beau-frère\"" },
{ "value": "16", "label": "\"Un autre lien familial\"" },
{ "value": "17", "label": "\"Un colocataire, sous-locataire\"" },
{ "value": "18", "label": "\"Autre lien (employé de maison, salarié logé, jeune au pair …)\"" }
