### ISSUE TITLE
Suggester : Data are not collected and that throws and error when go back in suggester

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#370]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/81740200/203512619-51279fc9-8a28-4d9c-ad23-c9036ae280d7.png">

**Comment by ddecrulle** [comment]
This issues is not a lunatic issues. 

This bug appeared when the id of the nomenclature is not a string.

**Comment by ddecrulle** [comment]
To avoid this, nomenclaure should valid this JSON schema 

```json
{
  "type": "array",
  "items": {
    "bsonType": "object",
    "required": [
      "id"
    ],
    "properties": {
      "id": {
        "type": "string"
      }
    }
  }
}

```

**Comment by AnneHuSKa** [comment]
Nomenclatures have been corrected. Thank you !
