### ISSUE TITLE
Comment évaluer la présence d'une réponse  ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#389]
Si elle l'est, comment est évaluée la présence d'une réponse (sans évaluer la validité) saisie dans un composant ?
par exemple:

* présence de texte dans un input text (notamment suite à l'effacement d'une saisie)
* présence d'un nombre entier dans un input number
* chaque bloc de boutons radio/checkbox avec une valeur sélectionnée
* Refus/Ne sait pas sélectionné

Actuellement queen recherche dans les bindings (variables et missing) pour vérifier la présence d'une valeur -> ce n'est plus possible avec la V2

**Comment by SimonDmz** [comment]
Le besoin est de gérer quand proposer de passer au composant suivant pour les composants à réponse non instantanée (plusieurs interactions utilisateurs possibles avant validation de la réponse saisie)

**Comment by laurentC35** [comment]
Le getState exposé par Lunatic ne permet pas de répondre à la question ?
Sinon il faut réfléchir à exposer un nouveau service par Lunatic
