### ISSUE TITLE
Focusable Components

### ISSUE THREAD

**Issue by SimonDmz** [InseeFr/Lunatic#396]
Components autofocus can't be provided from Orchestrator anymore

Previously in Lunatic : [component]Wrapper check if  `focused` attribute is passed in props, then [triggers the focus with useEffect hook](https://github.com/InseeFr/Lunatic/blob/32afb31250354b7bdc51cb640af3fae521f046a7/src/components/declarations/wrappers/input-declarations-wrapper.js#L60-L62)

**Comment by laurentC35** [comment]
New implementation in progress

**Comment by ddecrulle** [comment]
#664

**Comment by laurentC35** [comment]
Fix with #661
