### ISSUE TITLE
Placeholder text for the suggester

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#398]
🇬🇧 

The suggester component provides out-of-the-box a placeholder text.

From the [code ](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/suggester/suggester.js#L106) and the [Suggester part of the storybook v2](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/components-suggester--default) the default text seems to be "Veuillez...".

(Note : the [Logement questionnaire in the storybook ](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/questionnaires-logement--default) provides another placeholder, why?)

Some users don't understand that they need to start typing first.

A good solution would be to provide a cleverer text:

- in english "Start typing..."
- in french "Commencez votre saisie..."

in order to suggest typing to the user.

The french version may be provided by the relevant orchestrator (Stromae V2) whereas the english one should be the defaut one in Lunatic.

🇫🇷 

Le composant d'autocomplétion fournit par défaut un texte avant saisie (_placeholder_).

D'après le [code ](https://github.com/InseeFr/Lunatic/blob/v2-master/src/components/suggester/suggester.js#L106) et le [storybook](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/components-suggester--default) le texte par défaut est "Veuillez...".

(Note : c'est une autre histoire dans [le questionnaire Logement](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/questionnaires-logement--default) du même storybook, pourquoi ?)

Certains utilisateurs ne comprennent pas d'emblée qu'ils doivent commencer la saisie.

Une bonne solution serait de fournir :

- en anglais "Start typing..."
- en français "Commencez votre saisie..."

pour suggérer à l'utilisateur de commencer à taper.

La version anglaise serait le texte par défaut dans Lunatic, la version française pouvant être fournie par l'orchestrateur appelant.

**Comment by AnneHuSKa** [comment]
Lunatic 2.4.2 et Stromae 2.4.2 ok !
