### ISSUE TITLE
No saving of some filtered data in a loop - Bug "Famille"

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#399]
Comportement sur un questionnaire composé d'une boucle de séquences.
Exemple : une boucle de 2 individus
- je saisis les données de l'un des individus, je sors : pas de souci à la reconnexion, toutes les données sont sauvegardées.
- je me reconnecte, je commence à saisir les données de l'autre individu, je me déconnecte : à la reco, j'ai perdu les questions "doublement filtrées" du premier individu.
- je saisis les 2 individus, je me déconnecte et à la reconnexion, tout a été sauvegardé.

**Comment by AnneHuSKa** [comment]
Questionnaire plus simple présentant le pb. https://pogues-sandbox.demo.insee.io/questionnaire/ldndehwy : la donnée disparait lorsqu'on entre dans la 2eme boucle

**Comment by AnneHuSKa** [comment]
Si on enlève un des filtres (celui sur VITICI dans l'exemple), alors rien ne se perd

**Comment by BulotF** [comment]
Vu avec Jonathan...
Le problème ne vient pas de "resizing" (changement du nombre d'occurrences), mais de "cleaning" (nettoyage des réponses lorsqu'on passe un filtre de "affiché" à "caché")
cleaning ne tient pas compte de l'occurrence de boucle...

Jonathan vient de faire un travail similaire sur resizing dans le cadre des boucles de boucles (ex : changer le nombre de professions du 3° individu du 2° ménage, sans toucher aux autres). Il va l'adapter et le transposer sur cleaning.

**Comment by AnneHuSKa** [comment]
Lunatic 2.4.1 ok - Stromae ok
