### ISSUE TITLE
Label Position 

### ISSUE THREAD

**Issue by isMattCoding** [InseeFr/Lunatic#404]
The labels have been refactorised and separated from the components.  In a well-formed design system, the labels should be rendered directly with the component. This is the case in the DSFR. 
It would be preferable to restructure the components so that the labels are included in and rendered by each component.

**Comment by AnneHuSKa** [comment]
ok, go ahead, :-)

**Comment by AnneHuSKa** [comment]
Is it the same issue as this one : https://github.com/InseeFr/Lunatic/issues/274 ?

**Comment by isMattCoding** [comment]
> Is it the same issue as this one : #274 ?

It's related, in the sense that the components in the first point of issue #274 need to be reconsidered.  
In the second point, it is not clear whether the intention is to leave the labels as `<span>` or to change them to `<label>`. 
To be clear, our intention is to replace the `<span>` on all composants that require a `<label>`, and to ensure that the `<label>` is rendered at the composant level, and not rendered separately.
