### ISSUE TITLE
Dynamic Arrays

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#409]
:fr:
Cas d'usage :
- tableau dynamique non personnalisé : n colonnes, nb_max lignes qui sont ajoutées (présence d'un bouton Ajouter).
- tableau dynamique prérempli avec des données (d'un échantillon), sans possibilité d'ajout de ligne : les cellules préremplies sont non modifiables (exemple : TIC).
- tableau dynamique prérempli avec des données (d'un échantillon), avec possibilité d'ajout de ligne : les cellules préremplies sont non modifiables (exemple : ESA).

Besoin : pouvoir controler les réponses de type libellé (EAP) pour ne pas permettre la création de doublons

**Comment by MickaelMenet** [comment]
Base de d'échange : dynamic-array.demo.insee.io  ?

**Comment by AnneHuSKa** [comment]
- absence des controles au sein d'une ligne :
- page orange qui s'affiche en sortant du questionnaire
- perso à tester avec fichier perso

**Comment by MickaelMenet** [comment]
page orange qui s'affiche en sortant du questionnaire => problème dans les numéros de pages corriger manuellement

**Comment by AnneHuSKa** [comment]
Vérification faite : je n'avais pas modifié manuellement  les numéros de page, c'est bien Eno qui ne génère pas bien les numéros de page : on dirait qu'on compte le nombre de lignes max pour calculer le nb de pages.

**Comment by nsenave** [comment]
C'est le nombre de colonnes qui est comptabilisé pour le calcul des numéros de page : Eno v2 doit probablement comptabiliser chaque composant défini à l'intérieur du `"RosterForLoop"`.

J'ai ajouté une 5ème "information mesurée" = 5ème colonne = 5 composant dans Lunatic, ça augmente de 5 le numéro de page du composant suivant.

Si c'est utile à court terme, ça devrait être facile à corriger dans Eno v2 (👋  @BulotF )

Côté v3, on vérifiera que la numérotation fonctionne bien en présence d'un `"RosterForLoop"` (👋  @davdarras )

**Comment by BulotF** [comment]
Pour Eno V2 : https://github.com/InseeFr/Eno/pull/649

**Comment by AnneHuSKa** [comment]
@Grafikart : un json plus complet puisque j'ai tenté d'y mettre des controles et j'ai supprimé des variable Declarations qui trainaient à tort
[json_tabdyn_avecControles.zip](https://github.com/InseeFr/Lunatic/files/13173751/json_tabdyn_avecControles.zip)

**Comment by Grafikart** [comment]
@AnneHuSKa Dans le JSON il faut remplacer "header" par "headers". 

De mon côté j'ai identifié un problème de rendu (cf https://github.com/InseeFr/Lunatic/pull/745).

Pour les contrôles en revanche c'est plus compliqué.
Pour le système de roundabout il y a un truc en place qui permet de lancer les contrôles sur chaque itération ce qui donne le retour visuel suivant (le libellé doit être adapté pour indiquer la ligne concerné): 

![image](https://github.com/InseeFr/Lunatic/assets/395137/5fc73faa-afd5-4f83-bdb1-f3b9c7dd4e81)

```diff
{
+	"type": "roundabout",
	"id": "jrc3ye5q-format-borne-inf-sup",
	"typeOfControl": "FORMAT",
	"criticality": "ERROR",
+	"iterations": { "value": "TABDYN3", "type": "VTL" },
	"control": {
		"value": "not(not(isnull(TABDYN2)) and (0>TABDYN2 or 100<TABDYN2))",
		"type": "VTL"
	},
	"errorMessage": {
		"value": "\" La valeur doit être comprise entre 0 et 100.\"",
		"type": "VTL|MD"
	}
},
```

Maintenant si on veut afficher l'erreur dans le tableau pour chaque champs, je pense qu'il faut qu'on réfléchisse à une nouvelle modélisation et aussi à l'affichage.

- Si on veut gérer un contrôle spécifique à la ligne on peut imaginer avoir un nouveau type "row", mais le problème d'où afficher l'erreur apparait
- Si on veut un contrôle spécifique à une cellule (un champs) dans ce cas là je pense que le control doit être déplacé sur le composant au sein du tableau de components du RosterForLoop et ajouter le code pour explorer les contrôles de manière récursive.

**Comment by romaintailhurat** [comment]
On cherche dans un premier temps à porter l'existant, or aujourd'hui pour les tableaux dynamiques de la filière entreprise :
- au niveau cellule on n'a que des contrôles de format (par exemple un entier entre 10 et 100)
- les contrôles de cohérence (ceux spécifiés via VTL par les concepteurs) ne sont appliqués que sur la colonne : si j'écris dans Pogues `$VAR$ > 100` le contrôle se déclenchera si la somme des champs de la "colonne" VAR est supérieure à 100.
- on n'a pas de contrôles par ligne.

Je ne crois pas qu'on doivent viser autre chose pour la cible à court terme pour limiter l'effort de conversion des questionnaires entreprise mais c'est à discuter.

**Comment by AnneHuSKa** [comment]
@Grafikart @romaintailhurat On a aujourd'hui des contrôles de cohérence par ligne (exemple : OFATS : 
``
$nb_modalite_B2$ <5 and $B2CROIS$ ='' and $B2COD_P$ <> '' and $B2COD_ACT$ <>'' ``, contrôle affiché sous le tableau).

Et je ne crois pas qu'aujourd'hui les contrôles par colonne soient fonctionnels mais c'est une demande forte.

![image](https://github.com/InseeFr/Lunatic/assets/71011059/82df00e8-0070-4651-940e-3db8d2431793)

**Comment by romaintailhurat** [comment]
@Grafikart Est-ce que cette explication visuelle précise suffisamment les choses ?

![image](https://github.com/InseeFr/Lunatic/assets/1663283/dd020fb7-8f48-4a10-9079-0fa06fba66d6)

L'idée étant :
- on empile les erreurs sous le tableau, en ordonnant : les erreurs de format puis les erreurs suite à des contrôles de cohérence. Les erreurs de format dans l'ordre de ligne, et à l'intérieur d'une ligne par ordre de colonne
- les erreurs de format sont aussi signalées en entourant le champ problématique

Concernant la modale, il nous semble peu efficace d'y reprendre l'ensemble des messages d'erreur, le tableau étant masqué c'est peu lisible, pourrait-on avoir un message générique dans ce cas-là ("Il y a des erreurs dans vos réponses au tableau") ?

En parallèle à ton retour, on va en discuter avec Julia sur Stromae V3, pour savoir si la question de la modale à du sens dans le nouvel orchestrateur (la modale n'étant plus une modale). Donc, ton retour à la proposition qu'on fait ici est important mais le design peut encore changer. 😓 

_NB_ pour les messages des contrôles de cohérence, on passera la consigne aux concepteurs de donner des éléments d'identification - le plus simple étant de rappeler la valeur problématique (un SIRET, le montant du chiffre d'affaire, etc.)

**Comment by romaintailhurat** [comment]
_Addendum_ Idéalement, les messages d'erreurs de format devrait plutôt se trouver sous le champ idoine.

**Comment by BulotF** [comment]
@Grafikart : pour les headers des tableaux dynamiques, on souhaiterait améliorer l'uniformisation et passer de headers à header dans Lunatic.
En effet, au niveau d'Eno et de Lunatic-model, on a header, aussi bien pour les tableaux dynamiques que pour les tableaux normaux.

Les deux sous-composants étant spécifiés de la même manière dans les différentes modélisations (Pogues-model ; DDI ; Lunatic-Model ; html), j'avais pensé qu'il était même possible de factoriser les header des deux composants (sauf si les conserver séparés a du sens)

P.S. Désolé : je suis passé à côté de ton retour lors des vacances de la Toussaint...

**Comment by AnneHuSKa** [comment]
@Grafikart à l'occasion si tu as une idée sur ce choix du s stp ? merci et merci à  @BulotF

**Comment by nsenave** [comment]
@romaintailhurat to be tested to be sure

**Comment by romaintailhurat** [comment]
Headers are fixed, we are looking forward to use the controls now, in which version of Lunatic @Grafikart ?

**Comment by Grafikart** [comment]
@romaintailhurat It should be in the 2.7

**Comment by romaintailhurat** [comment]
Current status:

- cell and table controls are operational
- row ones are not

**Comment by romaintailhurat** [comment]
Row controls are fixed ❤️

**Comment by romaintailhurat** [comment]
A working Lunatic JSON including all three types of controls 👇 

[tableaux-dynamiques-dans-la-filiere-avec-controles.zip](https://github.com/InseeFr/Lunatic/files/14039016/tableaux-dynamiques-dans-la-filiere-avec-controles.zip)

**Comment by AnneHuSKa** [comment]
The lunatic Json is no more available
