### ISSUE TITLE
ordonnancement de la recherche du suggester 

### ISSUE THREAD

**Issue by renaud23** [InseeFr/Lunatic#420]
Après échange avec Julien Guay, il faut mettre à jour la fonctionnalité de recherche des web-workers. Les résultats obtenus doivent-être liés aux tokens issus de la recherche et non à ceux correspondant dans l'index.
Par exemple, elec peut correspondre à la fois à électronicien et électricien. On a 2 racine lemmatiques dans l'index pour un seul token de recherche. Il faut donc regrouper ces résultats avant de scorer.

**Comment by renaud23** [comment]
Après recherche dans la fonctionnalité, le problème provenait des doublons éventuels par token de recherche. Un document pouvais ressortir plusieurs fois pour un même mot de recherche, parce que celui-ci est proche de plusieurs token d'indexation. Cela accroissait son poids dans le calcul du score. Si l'on prenait en compte TF, cela aurait du sens, mais ce n'est pas le cas de Meloto.

**Comment by AnneHuSKa** [comment]
Version en production le 14 juin
