### ISSUE TITLE
 useLunatic SHOULD find lastReachedPage from COLLECTED data

### ISSUE THREAD

**Issue by MickaelMenet** [InseeFr/Lunatic#424]
If there is a COLLECTED data for page18 question, it is expected that the useLunatic function return a pager with `lastReachedPage="18"`.
currently lastReachedPage is set to the parameter `initialPage` value : '1' by default
SIDE EFFECT => prevent breadcrumb from returning the right evaluation of reachability (based on lastReachedPage)

**Comment by AnneHuSKa** [comment]
Do I have to do anything @MickaelMenet?

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/302
