### ISSUE TITLE
Erreur instanciation boolean false d'un data existant getInitalValueFromCollected

### ISSUE THREAD

**Issue by PaulBOURGEAIS** [InseeFr/Lunatic#476]
Soucis au niveau de l'instanciation de l'orchestrateur lorsqu'il y a une variable booleenne à false. Exemple : On donne en entrée de useLunatic un data qui contient une variable ISEXCEPTIONNALDAY: false, et lorsque l'orchestrateur a fini de s'instancier, cette variable a été remise à null à cause d'une erreur dans l'init des valeurs : getInitalValueFromCollected(variable);

fromData vaudra toujours null dans le cas ou la valeur d'un boolean est false, et donc je pense qu'aucun boolean ne fonctionne lorsqu'il est défini à false qu'il n'est pas dans une boucle (array).
 Il semble qu'il suffirait de remplacer fromData = COLLECTED || FORCED par fromData = COLLECTED ?? FORCED dans src/use-lunatic/reducer/reduce-on-init.ts ligne 28. 

Cette solution est proposée suite a un debug, mais je n'ai pas de moyens de vérifier d'éventuels impacts.

**Comment by Grafikart** [comment]
Il y a moyen de me donner un exemple de JSON donné à useLunatic() pour reproduire ce problème ? 
Cela concerne qu'elle version ?
