### ISSUE TITLE
Replace inline style by a class

### ISSUE THREAD

**Issue by jdirand** [InseeFr/Lunatic#490]
We have an inline style on a paragraph (markdown component: style="margin: 0px;") that messes with lunatic-dsfr. Can we please move it to a class?
Thanks

![image](https://user-images.githubusercontent.com/5951368/228563592-16269c4f-6225-4705-8752-60d0bce01a1d.png)

**Comment by Grafikart** [comment]
What branch are you using from lunatic ? main / develop / v1 ?

**Comment by jdirand** [comment]
> What branch are you using from lunatic ? main / develop / v1 ?

We are using develop

**Comment by Grafikart** [comment]
Ok could you give me the json corresponding to this field ?

**Comment by renaud23** [comment]
https://github.com/InseeFr/Lunatic/blob/develop/src/components/commons/components/md-label/md-label.tsx

line 10
