### ISSUE TITLE
Unités : rendre dynamique l'unité d'une cellule d'un tableau

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#493]
Besoin EAP : disposer d'unités qui soient dynamiques (formule VTL qui la prend par exemple d'une variable externe)
Mémo : autre besoin de la filière xforms, enquête ACEMOPIPA

**Comment by laurentC35** [comment]
Duplicated : https://github.com/InseeFr/Lunatic/issues/668
