### ISSUE TITLE
Vidage des réponses aux questions filtrées en cas de retour sur la question filtrante : QCM (checkBoxGroup)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#504]
Le cleaning qui permet de supprimer les réponses aux questions filtrées en cas de correction de la variable filtrante ne fonctionne pas pour les QCM
Exemple dans le json joint, il me semble qu'il manque 
    "FILTRE3": {
      "QCM11": "(FILTRE3 = \"2\")",
      "QCM12": "(FILTRE3 = \"2\")",
      "QCM21": "(FILTRE3 = \"2\")",
      "QCM22": "(FILTRE3 = \"2\")"
    } 
[non_vidageQCM.zip](https://github.com/InseeFr/Lunatic/files/11250164/non_vidageQCM.zip)

**Comment by Grafikart** [comment]
Tu peux me donner les étapes pour reproduire (observer le problème) ? Le processus de remplissage du formulaire en question.

**Comment by AnneHuSKa** [comment]
Merci, je vais essayer, tu me diras si ca te semble "lisible" ?
**Question 1** : cocher "je ne filtre pas les questions (filtre1 = "2")
Input1 (variable QNUM1) : saisir 1
Input2 (variable QNUM2) : saisir 1
Input3 (variable QNUM3) : saisir 1 
Revenir à Question 1 : cocher cette fois "je filtre les questions (filtre1 = "1")
Changer de page (on arrive donc à question 5)
Revenir à Question 5 : cocher de nouveau "je ne filtre pas les questions (filtre1 = "2")
Changer de page
On retombe sur Input1 qui a été vidée, à raison

**Question 5** : cocher "je ne filtre pas les questions (filtre2 = "2")
QCU1 (variable QCU1) : cocher AAAA
QCU2 (variable QCU2) : cocher AAAA
Revenir à Question 5 : cocher cette fois "je filtre les questions (filtre2 = "1")
Changer de page (on arrive donc à question 8)
Revenir à Question 5 : cocher de nouveau "je ne filtre pas les questions (filtre2 = "2")
Changer de page
On retombe sur QCU1 qui a été vidée, à raison

**Question 8** : cocher "je ne filtre pas les questions (filtre3 = "2")
QCM1 (variable QCM1) : cocher AAAA et BBBB
QCM2 (variable QCU2) : cocher AAAA
Revenir à Question 8 : cocher cette fois "je filtre les questions (filtre3 = "1")
Changer de page (on arrive donc à Commentaire)
Revenir à Question 8 : cocher de nouveau "je ne filtre pas les questions (filtre2 = "2")
Changer de page
On retombe sur QCM1 qui est toujours remplie, à tort

**Comment by Grafikart** [comment]
Désolé je n'avais pas compris le problème. Si il manque le cleaning correspondant à "FILTRE3" dans le JSON ce n'est pas une issue liée à Lunatic mais à l'outil qui génère les JSON ([Poques](https://github.com/InseeFr/Pogues) il me semble)

**Comment by laurentC35** [comment]
Peut-on fermer l'issue Lunatic du coup ?
Merci :)
