### ISSUE TITLE
Chargement initial d'un suggester

### ISSUE THREAD

**Issue by renaud23** [InseeFr/Lunatic#506]
Lorsque un utilisateur arrive pour la première fois, si le suggester est sur la première fois, la fin de l'initialisation ne se termine pas l'affichage du champ de suggestion. Le composant continue à afficher en cours de chargement.
Le problème ne se produit que lorsque l'on surcharge le composant SuggestionNotification. Le code actuel de Lunatic semb le fonctionnel.
Pour reproduire le bug, il faut veiller à détruire les stores avant de lancer la story.

**Comment by AnneHuSKa** [comment]
@renaud23 : c'est ce que tu corriges avec  "Votre référentiel est en court de chargement. Vous pouvez poursuivre le questionnaire et revenir ultèrieurement sur cette question." ?
On l'a en recette coté StromaeV2, ca fonctionne très bien mais 2 petites coquilles (c'est coté Lunatic ?): 
- en court => en cours 
- ultèrieurement => ultérieurement 

merci

**Comment by AnneHuSKa** [comment]
(Ophélie je recette : recette Stromae : 2.4.1 | Lunatic : 2.4.2 | Eno  2.4.1-pairwise)
