### ISSUE TITLE
Feat: A composant to create a `<fieldset>` with a `<legend>` and one or more componants

### ISSUE THREAD

**Issue by isMattCoding** [InseeFr/Lunatic#510]
### Current situation 

Currently a question in an enquete can be posed using the following format: 

```
[PAGE]
    <Sequence>     =>eg. "What's your name?" 
    <Componant>  =>eg. *Input* 
[/PAGE] 
```
This is satisfactory if the question requires only one componant to respond, but it does not satisfy the case where the question evokes more than one componant to respond as it does not satisfy the norms of html that are required for accessibility reasons (see: https://www.w3.org/WAI/tutorials/forms/grouping/) 

### Proposed solution 

A componant that allows multiple componants to be grouped (in a `<fieldset>`) and relate to the same question (encapsulate in the `<legend>`. 

eg: 
```
<fieldset id="question-one">
    <legend>Who are you?</legend> 
    <!-- Here we can add one or more lunatic components -->
    <!-- eg: First Name (Input), Last Name (Input), Date of Birth (Datepicker), Gender (Radio) -->
<fieldset> 
```

Following discussions with the product and development teams, this componant should be called `ComponentsSet`, which indicates that it is a set of multiple components grouped together, because they relate to the same question. 

It should be possible to have multiple  `ComponentsSet`s on one page. 
It should be possible to have one or more `ComponentsSet` on a page within a loop or a roundabout. 

PR in progress, to be submitted for review week of 24 April.

**Comment by romaintailhurat** [comment]
One last though: should it be named `ComponentSet` (singular) instead of `ComponentsSet` (plural)? I think it would be aligned with `fieldset` for example.
