### ISSUE TITLE
Consistency problem between a Lunatic type and the Eno/Lunatic output

### ISSUE THREAD

**Issue by bwerquin** [InseeFr/Lunatic#515]
I have a type consistency problem between an Eno output "lunaticModelVersion": "2.3.1", "enoCoreVersion": "2.4.1" and the description of the "source" type in Lunatic: the pagination is declared as "boolean" (https://github.com/InseeFr/Lunatic/blob/main/src/use-lunatic/type-source.ts#L300) while Eno generated me the "pagination": "question".

**Comment by AnneHuSKa** [comment]
EnoJava+ LunaticModel => pagination?: 'question' | 'sequence' | 'subsequence';
