### ISSUE TITLE
Contourner les restriction liées aux déclarations

### ISSUE THREAD

**Issue by renaud23** [InseeFr/Lunatic#516]
Les modifications liées à la refonte de la présentation des question dans le formulaire rendent difficile l'usage des déclarations.
Une extension du modèle doit être proposer  pour permettre d'ajouter des éléments textuels avant et au sein de certain composant comme proposé par la refonte de l'UX et de l'UI.

**Comment by renaud23** [comment]
Je propose l'ajout de 2 composants 
- InformationMessage
- contentMessage
Leur position au sein des composants sera imposé par design et non un choix libre du concepteur d'enquête.
Leur utilisation se fera au travers d'attribut des composants (informationMessage et contentMessage), Description est déjà pris par ailleurs.
Aucune régression ou conflit avec les déclarations ne devra être introduite, qui devront fonctionner comme par le passé.

**Comment by AnneHuSKa** [comment]
Info JD : 
Composant 1 : 
Nom DSFR : Call out / Mise en avant
Usage :  Afficher une information contextuelle à l'usager avant la question 
Composant 2 : 
Nom DSFR : Alerte de type information
Usage : Apporter un complément d'information importante à l'usager pour l'aider à répondre à la question 

=> Composant 1: QuestionContext      et      Composant 2: QuestionInformation

**Comment by AnneHuSKa** [comment]
@jdirand : ces 2 composants (Composant 1: QuestionContext et Composant 2: QuestionInformation) ont été ajoutés ou pas ?
Merci
@romaintailhurat : pour mémoire

**Comment by jdirand** [comment]
Oui nous les utilisons dans le rp
