### ISSUE TITLE
Unable to load workers for the suggester with Vite

### ISSUE THREAD

**Issue by bwerquin** [InseeFr/Lunatic#518]
process.env is not defined with Vite. The resolution of https://github.com/InseeFr/Lunatic/blob/main/src/utils/suggester-workers/append-to-index/create-append-task.ts#L5 cannot be done. With Vite, environment variables are only accessible with import.meta.env.

**Comment by laurentC35** [comment]
Fixed with :
- https://github.com/InseeFr/Lunatic/pull/741
- https://github.com/InseeFr/Lunatic/pull/751
- https://github.com/InseeFr/Lunatic/pull/757
