### ISSUE TITLE
Bug workers path

### ISSUE THREAD

**Issue by renaud23** [InseeFr/Lunatic#527]
Dans stromae, le suggester recherche une version des workers différentes de celle précisé dans l'application.
Dans lunatic, le script recherche dans dans process.env et met cette valeur dans une variable, à la racine du script. Au build, il doit probablement enfermer la valeur issue du fichier .env de lunatic et la rend inchageable depuis les applications ultilisateurs.
Enfermer cette recherche dans une fonction appelé dynamiquement devrait résoudre le problème.

**Comment by laurentC35** [comment]
Fixed with :
- https://github.com/InseeFr/Lunatic/pull/741
- https://github.com/InseeFr/Lunatic/pull/751
- https://github.com/InseeFr/Lunatic/pull/757
