### ISSUE TITLE
Update TrevasJS to 0.1.18

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#561]
There's a new [TrevasJS](https://www.npmjs.com/package/@inseefr/trevas) in town. This version comes with a more complete `in` and `not_in` support (see [this](https://inseefr.github.io/Trevas-JS/storybook/?path=/story/interpretor-comparison--in-not-in)).

**Comment by MickaelMenet** [comment]
Mise à disposition de trevas dans sa version 0.1.18 sur un environnement stromae disponible : https://trevas0-1-18.demo.insee.io/visualize

**Comment by romaintailhurat** [comment]
Works like a charm.

**Comment by romaintailhurat** [comment]
In which version of Lunatic will it be delivered?
