### ISSUE TITLE
Datepicker - HS en tactile (rien n'est cliquable)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#563]
Et comme la saisie est compliquée en "saisie directe", saisie date presque impossible hors souris

**Comment by romaintailhurat** [comment]
Le composant ne marche pas bien globalement, il est très difficile d'usage au clavier. Pour reproduire [par exemple sur le storybook](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/components-datepicker--default):

- je vide le champ
- (pour 01/01/2000) je saisis d'abord "01"
- puis "01"
- puis je saisis "2" → le segment année devient "0002"
- je saisis "0" → le champ entier est réinitialisé
