### ISSUE TITLE
Refactor : Duration component

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#576]
This PR : https://github.com/InseeFr/Lunatic/pull/573 was merged too quickly without proper code review.

- `Duration` component is too big : [src/components/duration/duration.tsx](https://github.com/InseeFr/Lunatic/blob/develop/src/components/duration/duration.tsx)
- the "hook" [`useDurationValues`](https://github.com/InseeFr/Lunatic/blob/develop/src/components/duration/duration.tsx#LL30C37-L30C37) is not actually a hook, juste a classic JS function.
- the implementation of this "hook"[src/components/duration/useDurationValues.ts](https://github.com/InseeFr/Lunatic/blob/develop/src/components/duration/useDurationValues.ts) is too big. I think we have to split code to get the code more readable.

If anyone has good idea to refactor this, please suggest code with a PR.

**Comment by Grafikart** [comment]
Il serait bien dans ce cas de rollback le merge (vu que ce sont les derniers commits).

**Comment by MickaelMenet** [comment]
J'ai revert tout ce qui est lié à duration
