### ISSUE TITLE
Based-on loop is not working properly

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#583]
A strange case with this [questionnaire](https://pogues-beta-testeurs.demo.insee.io/questionnaire/ljea1lzg).

# Description & how to reproduce

In the original questionnaire - which is not working - we have the following structure in a loop:

![image](https://github.com/InseeFr/Lunatic/assets/1663283/b562f5db-d269-4c2e-b7d3-0f29cdbcd199)

The loop definition in Pogues is:

![image](https://github.com/InseeFr/Lunatic/assets/1663283/e7c2bbc2-fdb1-4dfa-a9b2-625b4fa65f57)

We are supposed to see N iteration of the loop, N being the iteration number of the `BOUCLE_PRENOMS` in this [referenced questionnaire](https://pogues-beta-testeurs.demo.insee.io/questionnaire/lgf69bqb).

But this is not happening. You can try the [following questionnaire](https://minio.lab.sspcloud.fr/romaintailhurat/public/bug/ljea1lzg-probleme-boucle-var-calc-KO.lunatic.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BQGHTNTVDHQBT2GFV9Y9%2F20230627%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230627T140746Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCUUdIVE5UVkRIUUJUMkdGVjlZOSIsImF0X2hhc2giOiI1NFl5U1FZdGowM28xampkdnRKUzRBIiwiYXVkIjoibWluaW8tZGF0YW5vZGUiLCJhdXRoX3RpbWUiOjE2ODc4NzQwNjYsImF6cCI6Im1pbmlvLWRhdGFub2RlIiwiZW1haWwiOiJyb21haW4udGFpbGh1cmF0QGluc2VlLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTY4Nzg3ODE0MSwiZmFtaWx5X25hbWUiOiJUYWlsaHVyYXQiLCJnaXZlbl9uYW1lIjoiUm9tYWluIiwiZ3JvdXBzIjpbXSwiaWF0IjoxNjg3ODc0NTQxLCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoiZDNjNmIwNDctMjIyMi00ZjU5LTlhN2UtZGVhMTI2NGExYWVkIiwibG9jYWxlIjoiZW4iLCJuYW1lIjoiUm9tYWluIFRhaWxodXJhdCIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyb21haW50YWlsaHVyYXQiLCJzZXNzaW9uX3N0YXRlIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic2lkIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic3ViIjoiZTNjMjMzMTYtMmJmMS00MmJlLWEyMGMtMmM2ZTRhMjA4YjBjIiwidHlwIjoiSUQifQ.15hKJShjcXSTy15QxhJrsLZjIm2z2pGmY9gyAUGLFQvY7BMv3sGa-WHpoZ_KoxypxcplB5yD7TrJIUvmEFLDFQ&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=78ba99cfcfb1ec1bde873950171b06c13356de3fc06e1a04d16da5bbaf0d088b) in the Lunatic storybook.

# Working cases

There are two cases when the questionnaire is working.

The 1st one is when we add in the last Sequence of the loop `AA` a declaration including the variable `T_ANNAIS` - used for the computing the `T_AGE` var used in the filter (see 1st screenshot).

The VTL formula is `if $T_ANNAIS$ then "" else ""`. You can check this behaviour with [the following Lunatic JSON](https://minio.lab.sspcloud.fr/romaintailhurat/public/bug/ljea1lzg-probleme-boucle-var-calc-OK-decl.lunatic.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BQGHTNTVDHQBT2GFV9Y9%2F20230627%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230627T140816Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCUUdIVE5UVkRIUUJUMkdGVjlZOSIsImF0X2hhc2giOiI1NFl5U1FZdGowM28xampkdnRKUzRBIiwiYXVkIjoibWluaW8tZGF0YW5vZGUiLCJhdXRoX3RpbWUiOjE2ODc4NzQwNjYsImF6cCI6Im1pbmlvLWRhdGFub2RlIiwiZW1haWwiOiJyb21haW4udGFpbGh1cmF0QGluc2VlLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTY4Nzg3ODE0MSwiZmFtaWx5X25hbWUiOiJUYWlsaHVyYXQiLCJnaXZlbl9uYW1lIjoiUm9tYWluIiwiZ3JvdXBzIjpbXSwiaWF0IjoxNjg3ODc0NTQxLCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoiZDNjNmIwNDctMjIyMi00ZjU5LTlhN2UtZGVhMTI2NGExYWVkIiwibG9jYWxlIjoiZW4iLCJuYW1lIjoiUm9tYWluIFRhaWxodXJhdCIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyb21haW50YWlsaHVyYXQiLCJzZXNzaW9uX3N0YXRlIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic2lkIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic3ViIjoiZTNjMjMzMTYtMmJmMS00MmJlLWEyMGMtMmM2ZTRhMjA4YjBjIiwidHlwIjoiSUQifQ.15hKJShjcXSTy15QxhJrsLZjIm2z2pGmY9gyAUGLFQvY7BMv3sGa-WHpoZ_KoxypxcplB5yD7TrJIUvmEFLDFQ&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=2eb0c78c87edd85d89075911423065a15740e9fdaf20d80f975cc56a1fd2177e).

A second working case is when we delete the filter on the referenced questionnaire (see 1st screenshot once again), see [this third questionnaire JSON](https://minio.lab.sspcloud.fr/romaintailhurat/public/bug/ljea1lzg-probleme-boucle-var-calc-OK-sans-filtre.lunatic.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BQGHTNTVDHQBT2GFV9Y9%2F20230627%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230627T140847Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJCUUdIVE5UVkRIUUJUMkdGVjlZOSIsImF0X2hhc2giOiI1NFl5U1FZdGowM28xampkdnRKUzRBIiwiYXVkIjoibWluaW8tZGF0YW5vZGUiLCJhdXRoX3RpbWUiOjE2ODc4NzQwNjYsImF6cCI6Im1pbmlvLWRhdGFub2RlIiwiZW1haWwiOiJyb21haW4udGFpbGh1cmF0QGluc2VlLmZyIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTY4Nzg3ODE0MSwiZmFtaWx5X25hbWUiOiJUYWlsaHVyYXQiLCJnaXZlbl9uYW1lIjoiUm9tYWluIiwiZ3JvdXBzIjpbXSwiaWF0IjoxNjg3ODc0NTQxLCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoiZDNjNmIwNDctMjIyMi00ZjU5LTlhN2UtZGVhMTI2NGExYWVkIiwibG9jYWxlIjoiZW4iLCJuYW1lIjoiUm9tYWluIFRhaWxodXJhdCIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJyb21haW50YWlsaHVyYXQiLCJzZXNzaW9uX3N0YXRlIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic2lkIjoiNDdkMmViZjItYmE0MS00NDU3LTg5MGUtNTdkOTA4ODI4NzQzIiwic3ViIjoiZTNjMjMzMTYtMmJmMS00MmJlLWEyMGMtMmM2ZTRhMjA4YjBjIiwidHlwIjoiSUQifQ.15hKJShjcXSTy15QxhJrsLZjIm2z2pGmY9gyAUGLFQvY7BMv3sGa-WHpoZ_KoxypxcplB5yD7TrJIUvmEFLDFQ&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=cc691ac45ed270092a2640b644b2159dff443d5f50facb27ae2666dd554bb428).

**Comment by romaintailhurat** [comment]
Links to Lunatic questionnaires are not working, here is a ZIP files →

[issue-583-lunatic.zip](https://github.com/InseeFr/Lunatic/files/11884488/issue-583-lunatic.zip)

**Comment by laurentC35** [comment]
@romaintailhurat Still an issue in 2.7 ?

**Comment by AnneHuSKa** [comment]
@romaintailhurat : en 2.7 encore ?

**Comment by romaintailhurat** [comment]
Still happening with the examples in attachment. Should we try to emulate that in a fresh questionnaire to be generated by Eno V3 ?
