### ISSUE TITLE
Filtered loop performance issues

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#590]
In some large questionnaires, having based-on and filtered loops make the response to fields in the original loop very slow (a user can be confused because writing for example "Severus" in a surname field will result in "Svrus" or something incomplete).

An important note: if the loop filter is deleted, the performance seems way better (in this case, the filter is `$PRENOM$ <> $PRENOMREF$`)

__How to reproduce:__

- paste the provided questionnaire in Lunatic storybook
- go the the question 12 "En vous comptant, combien de personnes habitent dans le logement situé à l’adresse null ?"
- answer "4"
- in the next question "Votre prénom", type a name

[example questionnaire](https://github.com/InseeFr/Lunatic/files/12003553/questionnaire-lent-boucle-filtre-lia0th1h.lunatic.zip)

**Comment by Grafikart** [comment]
D'après mes tests le problème vient du cleaning qui se fait à chaque changement de valeur et qui éxécute beaucoup d'expressions.

![image](https://github.com/InseeFr/Lunatic/assets/395137/cb6c87b1-3162-4a8c-81fa-72b63317573f)

Je n'ai pas forcément de piste d'optimisation si ce n'est peut être de voir si le cleaning ne pourrait pas être déplacé au changement de page
