### ISSUE TITLE
Suggester - Display the whole label

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#606]
> Estanp need, to be completed

Multiline display if needed.

See example below 👇 

![suggester-estanp-text-display](https://github.com/InseeFr/Lunatic/assets/1663283/696974e5-e90f-4197-933b-6be52e81328f)

**Comment by AgatheLM** [comment]
The whole label must also appear once selected.

**Comment by AnneHuSKa** [comment]
- affichage sur plusieurs lignes : ok https://github.com/InseeFr/Lunatic/issues/1059
- attendre la version Eno qui gère le multivariable pour le reste

**Comment by JulienCarmona** [comment]
@nsenave à check

**Comment by JulienCarmona** [comment]
Validation QF : ✅ 
Le label complet apparait bien quand il est sélectionné.
