### ISSUE TITLE
Suggester - Display a simple text when the suggester is disabled

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#607]
> Estanp need, to be completed

**Comment by laurentC35** [comment]
Can you clarify : Disabled or not available ?

**Comment by romaintailhurat** [comment]
The case we want to manage is the impossibility to load the list JSON file.

One way to do that would be to display a "Reload the page in order to see the list" when we cannot open the URL to the JSON file.

🇫🇷 "La liste des choix de réponse n'est pas disponible, veuillez recharger la page"
🇬🇧 "..."
