### ISSUE TITLE
Suggester - Hide the already selected items

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#608]
> Estanp need, to be completed

**Comment by laurentC35** [comment]
@AgatheLM 
What does "already selected" mean ?

- Already selected inside a table ?
- Already selected inside all form ?

**Comment by AgatheLM** [comment]
The first one : In th same table, so in a array variable

**Comment by romaintailhurat** [comment]
Too sophisticated, wont do now.
