### ISSUE TITLE
Dynamic table - Custom text for Add & Delete buttons

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#611]
> Estanp need, to be completed.

**Comment by romaintailhurat** [comment]
We would like to be able to overwrite the buttons label:

![image](https://github.com/InseeFr/Lunatic/assets/1663283/7f1da0ad-ab5d-4683-aca0-d67f9af46b75)

For example "Ajouter une ligne" would be change for "Ajouter un produit".

**Comment by AnneHuSKa** [comment]
Trop spécifique. Contexte de tableau : ajouter une ligne généraliste
