### ISSUE TITLE
Lunatic Data : A typo: INPUTED instead of INPUTTED

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#614]
Hey,

There is a typo in the Lunatic Collected data possible field. It should be INPUTTED instead. I believe it's the right time to correct this before the management mode is released. Currently, this only affects applications before Lunatic (Eno/Lunatic Model, and perhaps Pogues and Pogues Model). However, if left unaddressed, it could potentially impact numerous other applications and all those downstream from Lunatic in the future.

**Comment by nsenave** [comment]
It's done in Eno, generated questionnaires will have `"INPUTTED"` from now on.
