### ISSUE TITLE
Bug - dans une sous-séquence qui boucle, sélection d'une modalité de CheckBoxGroup filtré (par du hors boucle) impossible 

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#642]
Un bug pour l'enquête SD

- Une question filtrée _FILTRE_
- Une sous-séquence qui boucle de 1 à 10 occurrences (donc avec bouton ajouter) : la sous-séquence comprend 3 questions, dont une est un QCM CheckBoxGroup filtré sur la question _FILTRE_ 

Souci : les modalités de la question filtrée sont incochables.

Json en PJ (test https://inseefr.github.io/Lunatic/storybook-beta/?path=/story/behaviour-paste--default et avec Queen : 1.0.9 | Lunatic : 2.5.0-fix-last-reached-page)  

[issue642.zip](https://github.com/InseeFr/Lunatic/files/12461946/issue642.zip)

**Comment by ddecrulle** [comment]
Le bug est plus général, les réponses à choix multiples (Checkbox Group) ne fonctionnent pas dans les boucles.

**Comment by laurentC35** [comment]
The Sprin workflow close the issue (linked to #647 )
