### ISSUE TITLE
Very large questionnaire breaks around 500 pages

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#646]
Questionnaire with id  `llnxag09 ` in Pogues Insee

Sometimes, questionnaire is breaking during navigation.

**Comment by romaintailhurat** [comment]
More specifically, it breaks between pages 541 to 543 😄

**Comment by romaintailhurat** [comment]
👉  [Example of a broken questionnaire](https://visu-queen.demo.insee.io/queen/visualize?questionnaire=https%3A%2F%2Fminio.lab.sspcloud.fr%2Figkpla%2FBDF%2Fform_13_09.json&data=https%3A%2F%2Fminio.lab.sspcloud.fr%2Figkpla%2FBDF%2FdataBDF_ab.json&nomenclature=%7B%22L_COMMUNEPASSEE-1-2-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_COMMUNEPASSEE-1-2-0.json%22%2C%20%22L_DEPNAIS-1-1-0%22%3A%20%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_DEPNAIS-1-1-0.json%22%2C%20%22L_NATIONETR-1-1-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_NATIONETR-1-1-0.json%22%2C%20%22L_PAYSNAIS-1-1-0%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_PAYSNAIS-1-1-0.json%22%2C%20%22L_TTPTCM_ACTIVITES%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_TTPTCM_ACTIVITES.json%22%2C%20%22L_TTPTCM_DIPLOMES%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_TTPTCM_DIPLOMES.json%22%2C%20%22L_TTPTCM_PCSF%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_TTPTCM_PCSF.json%22%20%2C%22L_TTPTCM_PCSH%22%3A%22https%3A%2F%2Fminio.lab.sspcloud.fr%2Fabogner%2FBDF%2Fnomenclatures%2FL_TTPTCM_PCSH.json%22%7D).

Questionnaire: https://minio.lab.sspcloud.fr/igkpla/BDF/form_13_09.json

Data: https://minio.lab.sspcloud.fr/igkpla/BDF/dataBDF_ab.json

Nomenclatures:

```json
{
  "L_COMMUNEPASSEE-1-2-0": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_COMMUNEPASSEE-1-2-0.json",
  "L_DEPNAIS-1-1-0": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_DEPNAIS-1-1-0.json",
  "L_NATIONETR-1-1-0": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_NATIONETR-1-1-0.json",
  "L_PAYSNAIS-1-1-0": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_PAYSNAIS-1-1-0.json",
  "L_TTPTCM_ACTIVITES": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_TTPTCM_ACTIVITES.json",
  "L_TTPTCM_DIPLOMES": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_TTPTCM_DIPLOMES.json",
  "L_TTPTCM_PCSF": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_TTPTCM_PCSF.json",
  "L_TTPTCM_PCSH": "https://minio.lab.sspcloud.fr/abogner/BDF/nomenclatures/L_TTPTCM_PCSH.json"
}
```

**Comment by ddecrulle** [comment]
Checkbox one at page 543 do not provide options that cause an error. Maybe we could create another issue to implement a fallback behavior ?
