### ISSUE TITLE
Cleanup LastReachedPage

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#657]
The cleaning function, which deletes responses to filtered questions when the filter variable is corrected, does not recalculate the lastReachedPage parameter, which may change in this case.

**Comment by QRuhier** [comment]
vérifier le comportement lié (suite de l'entretien dans Queen) , voir si c'est satisfaisant ou nécessite de le revoir

**Comment by romaintailhurat** [comment]
1. Comportement à valider dans la dernière version de Queen
2. Si ça ne convient pas, on spécifie l'attendu.

**Comment by AnneHuSKa** [comment]
A relancer

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/1026
