### ISSUE TITLE
Suggester doesn't work in RosterForLoop and Table

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#674]
- getSuggesterStatus is missing in Row context in RosterForLoop/Table

**Comment by laurentC35** [comment]
Linked issue : https://github.com/InseeFr/Lunatic/issues/606 (style)

**Comment by AnneHuSKa** [comment]
Can we close @laurentC35 or is there a "technical point" (getSuggesterStatus missing ?)

**Comment by romaintailhurat** [comment]
Works like  charm for all types of table.
