### ISSUE TITLE
Refactor variables

### ISSUE THREAD

**Issue by Grafikart** [InseeFr/Lunatic#675]
At the moment variable collection and calculation are a bit complicated (executeExpression() is too complicated) and lots of things are stored in the state. This issue is here to discuss a possible refactoring of data collection.

## Idea 1 

The main problem is being able to evaluate expression less often. Here is my first draft

```ts
class LunaticVariable {
    #value: unknwon                                     // Value stored for the variable
    #updatedAt: number                              // Timestamp to track when a variable was last calculated / set
    #dictionnary:                                            // Dictionnary containing all the variables 
    dependencies: Set<LunaticVariable>  //  List of dependencies (calculated the first time the expression is parsed)
    expression: string | null                        // Expression for calculated Variable

    get value () {
        // With a getter we could calculate value on demand
        // Dependencies would be calculated when the value is first accessed
     }

    set value () {
       // Will update the updatedAt while setting the value
    }

}
```

We would need a dictionnary to retain all the variable. This dictionnary would be used by lunatic to retrieve a specific variable or an expression

```ts
const lunaticVariables = new LunaticVariablesRepository()
lunaticVariables.set('PRENOM', 'John');
lunaticVariables.set('NOM', 'Doe');
lunaticVariables.get('PRENOM');
lunaticVariables.get('PRENOM || NOM'); // It would create a variable to save this expression to avoid reevaluation
lunaticVariables.all() // get all variables
```

### The iteration issue

The main problem with this approach would be iterations. The value of an expression can change for a specific iteration. To solve this problem a variable could retain the value for every iteration. The iteration number would be used as the key for the map (key can be null for a variable calculated ouside of an iteration)

```ts
class LunaticVariable {
    #value: Map<null | number, unknown>  
    #updatedAt: Map<null | number, number>                                 // Timestamp to track when a variable was last calculated / set
    dependencies: Set<LunaticVariable>  //  List of dependencies 
    expression: string | null                        // Expression for calculated Variable

    getValue (iteration: number | null = null) {
        // With a getter we could calculate value on demand, instead of preventively
        // Dependencies would be calculated when the value is first accessed
     }

    setValue (iteration: number | null = null) {
       // Will update the updatedAt while setting the value
    }

}
```

### React and mutability

We could create an immutable structure for this dictionnary but since there is a lot of data it's not memory efficient. Also I don't think it should be saved in the state since variable are not accessed outside of the `getComponents()` or `getData()`. The dictionary can be saved in a ref used by these two methods, saving the "lastEditTime" in the state instead.

### Loop of loop

The nested loop feature will change the `iteration` shape from `number` to `number[]`. This is not an issue since we could use `iteration.join(',')` as a key to save or variable values.

**Comment by AnneHuSKa** [comment]
@laurentC35 @Grafikart on peut clore l'issue ?
