### ISSUE TITLE
Dropdown - placeholder

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#686]
🇬🇧

The Dropdown component provides out-of-the-box a placeholder text.

From the [storybook](https://inseefr.github.io/Lunatic/storybook-beta/?path=/story/components-dropdown--default)the default text seems to be "Please, do something..".

Some users don't understand that they need to start typing first.

A good solution would be to provide a cleverer text:

    in english "Start typing..."
    in french "Commencez votre saisie..."

in order to suggest typing to the user.

The french version may be provided by the relevant orchestrator (Stromae V2) whereas the english one should be the defaut one in Lunatic.

🇫🇷

La liste déroulante fournit par défaut un texte avant saisie (placeholder).

D'après le [storybook](https://inseefr.github.io/Lunatic/storybook-beta/?path=/story/components-dropdown--default) le texte par défaut est "Please, do something..".

(Note : c'est une autre histoire dans [le questionnaire Logement](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/questionnaires-logement--default) du même storybook, pourquoi ?)

Certains utilisateurs ne comprennent pas d'emblée qu'ils doivent commencer la saisie.

Une bonne solution serait de fournir :

    en anglais "Start typing..."
    en français "Commencez votre saisie..."

pour suggérer à l'utilisateur de commencer à taper.

La version anglaise serait le texte par défaut dans Lunatic, la version française pouvant être fournie par l'orchestrateur appelant.

**Comment by laurentC35** [comment]
Fix by : #688
