### ISSUE TITLE
ReadOnly props in all HTML compatible component

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#692]
This feature adds the possibility to define the readOnly attribute based on a VTL expression in the source.json.

Initially, this feature has only been added to the Input component and the Radio component. (note: the style of the Radio component with the readOnly attribute has not yet been updated to communicate visually that users cannot interact with it)

https://github.com/InseeFr/Lunatic/pull/628#issuecomment-1699059765

**Comment by AnneHuSKa** [comment]
Besoin rendu par composant texte
