### ISSUE TITLE
Answer to fields in main loop breaks the questionnaire

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#704]
__SD__ survey, with last versions of Queen

@AnneHuSKa will qualify the bug soon

**Comment by laurentC35** [comment]
The bug is only occured when questionnaire has a Loop base on a SubSequence ?

**Comment by romaintailhurat** [comment]
Also breaks in a sequence, see following questionnaire.

[lunatic-704-sequence.zip](https://github.com/InseeFr/Lunatic/files/12748018/lunatic-704-sequence.zip)

**Comment by laurentC35** [comment]
Possibly linked to this dev : https://github.com/InseeFr/Lunatic/pull/647

**Comment by Grafikart** [comment]
Is there an error displayed on the screen ? What are the step to produce the bug ? 

On Lunatic I have this issue (is it the right problem ?)
![image](https://github.com/InseeFr/Lunatic/assets/395137/ceb8f8b7-3fed-4bab-b727-2beb56a0c2a1)


From my point of view DATE and DATE_MISSING default value are incorrect since it's in a loop

**Comment by romaintailhurat** [comment]
In order to reproduce the bug (with one of the provided questionnaires in the upper comments):

- in a main loop field (date for example), typing or select an answer
- immediately an error page appears

In [my case](https://github.com/InseeFr/Lunatic/issues/704#issuecomment-1738826238), i get this error message (looks like the same as yours):

![image](https://github.com/InseeFr/Lunatic/assets/1663283/5d06a2ff-1287-413d-9dd9-43b277c6672e)

**Comment by Grafikart** [comment]
You add data to useLunatic or just the source.json ?

**Comment by romaintailhurat** [comment]
Sorry @Grafikart, i didn't see your previous comment: only the source.json (the questionnaire).
