### ISSUE TITLE
Declarations compatibility with Stromae v3

### ISSUE THREAD

**Issue by jdirand** [InseeFr/Lunatic#712]
We have noticed two problems with the declarations in Stromae v3 : 

- the AFTER_QUESTION_TEXT declarations are not showing up and make Stromae v3 crash: 
They should replaced the field "description" if the field "description" exist in a component.

- Only the DETACHABLE declarations are shown in a subsequence
We need to do the same thing as in a Sequence and add the "description" props to the SubSequence component. Then, we will need to adapt Lunatic-dsfr.

**Comment by Grafikart** [comment]
Could I have a JSON that produce the bug on Lunatic ?

**Comment by jdirand** [comment]
@Grafikart You can take this json here : https://inseefr.github.io/Lunatic-DSFR/?path=/docs/orchestratedcomponents-subsequence--docs and also see the problem in lunatic-dsfr

**Comment by Grafikart** [comment]
Dans le storybook de Lunatic j'obtiens ça : 

![image](https://github.com/InseeFr/Lunatic/assets/395137/cbf126e2-e4d7-40b7-8b92-5fcae2d2b5f0)

Aussi, peux tu m'indiquer ce que je dois changer car à première vu tout semble s'afficher sans erreur (côté lunatic en tout cas)

**Comment by AnneHuSKa** [comment]
@Grafikart je crois que le souci est dans StromaeV3 et Lunatic dsfr : avec le json de Julia, tu as 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/fe914a74-f794-4a2d-882c-26cef11db1d0)

mais dans dsfr tu as : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/324761de-a8e0-4e76-9be6-2a4b1f1826d5)

@jdirand si tu sais compléter ?

**Comment by jdirand** [comment]
Oui nous avons identifié que le problème vient de Lunatic-DSFR. Je vais regarder prochainement.
