### ISSUE TITLE
Pairwise when people have the same first name and last name

### ISSUE THREAD

**Issue by jdirand** [InseeFr/Lunatic#714]
The pairwise component is not showing up if people have the same first and last names.

**Comment by romaintailhurat** [comment]
https://github.com/InseeFr/Lunatic/blob/main/src/components/pairwise-links/row.tsx#L38 ?

**Comment by jdirand** [comment]
There were a conditonFilter on the story
					"conditionFilter": { "value": "xAxis <> yAxis", "type": "VTL" },
