### ISSUE TITLE
Suggester - compréhension des échos

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#716]
Dans l'enquête Cadre de Vie, l'absence de certains échos sur la liste d'Activités pose question (exemple pour mémoire : DANS = des échos dont DANSE // DANSE = aucun écho)

Qualification sur le storybook :  
https://inseefr.github.io/Lunatic/storybook-beta/?path=/story/components-suggester--default

![image](https://github.com/InseeFr/Lunatic/assets/71011059/fb4f031c-ce78-4877-90f6-bef951974c46)

**mais**
![image](https://github.com/InseeFr/Lunatic/assets/71011059/25089690-5a1b-4137-83dd-62c538a50f44)

donc plus d'échos ?

En cours de qualif par DRTI

**Comment by Grafikart** [comment]
Si j'ajoute à la recherche je remarque que la base de donnée index db contient les informations suivante pour le 38.12

![image](https://github.com/InseeFr/Lunatic/assets/395137/0293ef9e-2666-4126-aa51-9eaf9d53bfdc)

Le problème n'est donc pas sur la recherche mais sur l'indexation (je continue de chercher)

**Comment by AnneHuSKa** [comment]
@Grafikart : ne cherche plus merci, on me souffle dans l'oreillette qu'il faut ajouter un paramétrage STEMMER = false.
Je vais clore issue
