### ISSUE TITLE
`"rules"` property in fields of suggesters

### ISSUE THREAD

**Issue by nsenave** [InseeFr/Lunatic#784]
The `"rules"` property in the fields objects of suggesters configuration objects, is currently as follows:

> "rules" defines search behavior. It can be either a string or an array.
>
> - If string, only 'soft' is valid. The value 'soft' leads to a minimal transformation of the field ("La belle nuit de Noël" -> "la-belle-nuit-de-noel"). 
> - If array, list of regular expressions, e.g. to search on words, numbers etc.

Two (incomplete) examples where the property is valid in the current modeling:

```json
{
  "suggesters": [
    {
      "fields": [
        {
          "rules": "soft"
        }
      ]
    },
    {
      "fields": [
        {
          "rules": ["[\\w]+"]
        }
      ]
    }
  ]
}
```

➡️ This modeling should be changed so as not to use a property that can have different types.

### Proposal 1

Separate this property in two (mutually exclusive) properties, for instance:

- `"rule"` which would be a string (or even better an enum)
- `"rules"` being the array version as described above

### Proposal 1 B

Is the "array" mode, is it actually useful to have a list of regular expressions, and not simply a single expression instead?

If so, the property should be renamed as something clearer like `"pattern"`

### Proposal 2

Replace the value `"soft"` by an empty array `[]`. Empty array would implicitely mean that the rule is "soft".

NB: these proposals shouldn't require too much refactor in the code, yet neither seems perfectly satisfying to me. Feel free to _suggest_ something else.

**Comment by Grafikart** [comment]
J'aime bien la **Proposal 2** car elle permet d'avoir un type plus cohérent. 

Elle peut cependant être limitante si un nouveal algorithm vient à voir le jour. Peut être regroupé ça dans une clef "tokenParser" pourrait être plus explicite ? 

```ts
type tokenParser = {
   type: 'regex' | 'soft',
   expressions: string[]
}
```

Cela implique cependant des changements plus profond

**Comment by romaintailhurat** [comment]
@nsenave could you elaborate on this?

**Comment by nsenave** [comment]
Parfois le mieux est l'ennemi du bien... le travail est fait pour fonctionner avec la modélisation actuelle des `"rules"`, je close l'issue, on pourrait y revenir pour faire quelque chose de plus propre si on avait besoin de modifier (ce qui n'est pas prévu pour le moment).
