### ISSUE TITLE
In existing questionnaires, the Pairwise links component is not working anymore with Lunatic 2.7.4

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#792]
# How to reproduce

In the [Storybook for 2.7](https://inseefr.github.io/Lunatic/storybook-2.7/?path=/story/behaviour-paste--default), paste [this questionnaire](https://github.com/InseeFr/Bowie/blob/main/useful-questionnaires/validation/QnonregLiens2a2-LunaticCapi.json).

- Answer to the questions and add at least two persons in the household
- At page 5, see there no Pairwise component.

**Comment by romaintailhurat** [comment]
_Note_ The component directly used in the storybook [is working](https://inseefr.github.io/Lunatic/storybook-2.7/?path=/story/components-pairwiselinks--default).

Is this a problem with an update to the model?

**Comment by Grafikart** [comment]
Il y a plusieurs problème dans ce JSON.

## Absence du type

Celui qui fait que le pairwise ne s'affiche pas est celui ci : 

```json
"xAxisIterations": {"value": "count(PRENOM)"},
"yAxisIterations": {"value": "count(PRENOM)"},
```

Pour ces 2 variables le type est oublié et du coup le système ne l'interprète pas.

```diff
      "xAxisIterations": {
        "value": "count(PRENOM)",
+      "type": "VTL"
      },
      "yAxisIterations": {
        "value": "count(PRENOM)",
+      "type": "VTL"
      },
```

## Pas de conditionFilter sur les axes

Cette condition n'est plus nécessaire car le composant fait déjà cette condition en interne. Tu peux retirer le conditionFilter pour voir les dropdown s'afficher.

```diff
-          "conditionFilter": {
-            "value": "xAxis <> yAxis",
-            "type": "VTL"
-          },
```

## Guillemets dans le VTL (facultatif)

Aussi de nombreuses expressions ne sont pas entre guillemet ce qui plante le VTL dans certains calcul.

```diff

                    "label": {
-                       "value": "Description des habitants",
+                      "value": "\"Description des habitants\"",
                        "type": "VTL|MD"
                    },
```
