### ISSUE TITLE
Bug related to the format of the textfield control

### ISSUE THREAD

**Issue by philippe-clement** [InseeFr/Lunatic#8]
For every input composant the control works when you fill in the field with numbers 
but when you fill it with letters the controle seems to work but the message is not displayed.

**Comment by NicoLaval** [comment]
Seems to be a FF issue (Chrome only enable e or E as letter, ie exponential)

**Comment by philippe-clement** [comment]
What does ii mean ? no fix for FF with this issue ?

**Comment by NicoLaval** [comment]
Whatever the version of FF, it seems to be their choice.

We will reflect on whether it is appropriate to block foreclosures in our handler.

**Comment by NicoLaval** [comment]
Fix was not satisfying.
Cancel handle strategy for now.

Topic to study
