### ISSUE TITLE
Mauvaise interaction avec le cleaning et la valeur initiale d'une variable (affichage de questions à tort, affichage de modalités différentes)

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#817]
Partons d'un json dont la navigation est ok en 2.6 beta (https://inseefr.github.io/Lunatic/storybook-2.6)

Le même en 2.7 :
- affiche des questions/pages à tort (exemple 2 habitants, n° page 11/64 - filtre T_PCLCACLAIR | '(not(PRENOM <> PRENOMREF)) and (T_EMPLOI = "1") and (PRENOM = PRENOMREF) and (T_PCLCAF = "9999" or T_PCLCAH = "9999"), et plus globalement toutes les questions de la boucle qui ne devrait concerner que l'individu 1
- affiche des libellés de modalité à tort : page 46/97 Ouioui ou NonNon

Difficile de comprendre d'où ca vient et je n'arrive pas à créer un questionnaire suffisamment complexe.
Un Souci VTL ? mais pourquoi un impact aussi fort ?

[BugDoubleModalité.zip](https://github.com/InseeFr/Lunatic/files/13515864/BugDoubleModalite.zip)

**Comment by AnneHuSKa** [comment]
Un questionnaire plus simple (mais c'est juste le précédent, un peu élagué). Et questionnaire généré en web donc sans les missing).
soucis : 
- l'affichage de la page PageTag: "7.7#1" à tort (dans le json on voit bien "FILTER_RESULT_T_PCLCACLAIR": null)
- l'affichage des modalités de la page 11 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/3b7a248e-8a9b-4c2a-ae94-c90543d4dbc9)
J'envoie aussi les data MAIS quand je mets les data dans le storybook et que je vais directement en page 11, je n'ai pas le souci d'affichage des modalités (il faut vraiment faire des next jusqu'à la page 11, après avoir mis 2 habitants).. 

*Si ca aide, sur les modalités qui semblent poser souci, le concepteur a mis des codes du genre 1, 2, 80, 90 donc pas la même longueur pour toutes les modalités d'une liste ?*
[BugDoubleModalité_simple_DATA.zip](https://github.com/InseeFr/Lunatic/files/13527075/BugDoubleModalite_simple_DATA.zip)

**Comment by Grafikart** [comment]
Le problème a été identifié, une mauvaise interaction avec le cleaning et la valeur initiale d'une variable.

**Comment by AnneHuSKa** [comment]
MErci ! 
Les 2 soucis ? Affichage et navigation "inattendue" ?

**Comment by Grafikart** [comment]
Je n'ai pas le problème de la page 46 / 47 sur la dernière version sur le storybook.

![image](https://github.com/InseeFr/Lunatic/assets/395137/9a5b859f-7c59-4c2a-9122-33e1d223b99c)

**Comment by AnneHuSKa** [comment]
Double affichage également résolu
