### ISSUE TITLE
Suggester - PCS search is not working on Safari, possible deadlock on IndexedDB

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#821]
This is a stub, details will come from @Grafikart

**Comment by Grafikart** [comment]
Après investigation ça semble être un bug sur Safari

## Références

- Problème similaire sur Dexie : https://github.com/dexie/Dexie.js/issues/1030
- Thread twitter (2021) https://twitter.com/feross/status/1404568122158313474

## Pistes

- Peut être utiliser autour des requêtes : https://www.npmjs.com/package/safari-14-idb-fix

## Debug

Si j'essaie de supprimer toutes les bases de données avec ce code 

```js
indexedDB.databases().then(r => {
    r.map((table => {
        var req = indexedDB.deleteDatabase(table.name);
        req.onsuccess = function () {
            console.log("success" + table.name);
        };
        req.onerror = function () {
            console.log("can't delete " + table.name);
        };
        req.onblocked = function () {
            console.log("blocked " + table.name);
        };
    }))
})
```

On m'indique que la base de données est bloquée. 
- Si je ferme safari complètement et relance lunatic -> **bloqué**
- Si je ferme safari et ouvre un autre serveur web sur le meme port -> **débloqué**

**Comment by ddecrulle** [comment]
Problème réglé ? @romaintailhurat @jdirand @AnneHuSKa  ?

**Comment by romaintailhurat** [comment]
Corrigé en effet et intégré à Lunatic 2.6, est-ce que ça a été intégré également à la 2.7 ? @Grafikart @ddecrulle

**Comment by nsenave** [comment]
Intégré à la 2.7 @romaintailhurat
