### ISSUE TITLE
Simplify the usage of `if ... then ... else` VTL expressions

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#824]
In pure VTL, this expression:

```vtl
if true then "ok" else "ko"
```

returns the string `"ok"`

But in Lunatic a label or a variable made of the same expression will be returned in error. The workaround is to concatenate with - at least - an empty string:

```vtl
"" || if true then "ok" else "ko"
```

or

```vtl
if true then "ok" else "ko" || ""
```

We would like to be able to use the first and simpler expression.

**Comment by ddecrulle** [comment]
Did you tried `cast(if true then "ok" else "ko",string)` ?

**Comment by romaintailhurat** [comment]
> Did you tried `cast(if true then "ok" else "ko",string)` ?

But, but, that's even _uglier_ 😆

**Comment by romaintailhurat** [comment]
And in fact not working 🎆

**Comment by romaintailhurat** [comment]
Conclusion, it's not a problem on the Lunatic side but on the generation side.

The faulty code:

```json
"label": {
    "type": "VTL|MD",
    "value": "\"➡ 1. \" || \"if true then \"ok\" else \"ko\"\""
}
```

Note the `\"` at both ends of the `if...then...else` expression. This is working:

```json
"label": {
    "type": "VTL|MD",
    "value": "\"➡ 1. \" || if true then \"ok\" else \"ko\""
}
```
