### ISSUE TITLE
2.7 - recalcul des variables avec LIENS ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#832]
Un souci sur le calcul de certaines variables utilisant le concept de LIENS (quand on collecte les liens deux à deux - PAIRWISE).
(exemple tiré d'un cas usage TCM)
Le json et des data associées en pj

Exemple 
en 2.7 : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/58b7f068-1054-46dd-bee2-f808bbedfe18)
en 2.6 :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/42565b2b-114e-4e35-9551-932356c67642)

**Comment by AnneHuSKa** [comment]
[Issue832.zip](https://github.com/InseeFr/Lunatic/files/13648242/Issue832.zip)

**Comment by Grafikart** [comment]
@AnneHuSKa De mon côté je remarque un truc étrange dans le JSON 

```json
        {
            "variableType": "CALCULATED",
            "bindingDependencies": ["LIENS"],
            "expression": {
                "type": "VTL",
                "value": "if T_NBHAB > 3 then ( if (\"1\" in LIENS) and (\"3\" ....."
            },
            "name": "T_C_ENF_I",
            "inFilter": "true",
            "shapeFrom": "T_PRENOM"
        },
```

Je ne comprends pas ici que T_NBHAB ne soit pas en bindingDependencies car il est utilisé dans l'expression. Si je corrige cette erreur le formulaire fonctionne comme attendu.

**Comment by AnneHuSKa** [comment]
merci @Grafikart, c'est un json issu de la génération par le moteur Eno, donc un sujet à creuser de ce côté. Mais sans le T_NBHAB ca marchait "quand même" en 2.6. 
Cela te semble cohérent ? merci à toi

@nsenave @laurentC35 pour info pour Eno.

**Comment by Grafikart** [comment]
@AnneHuSKa Je peux le faire fonctionner en lui demander d'ignorer les bindingDependencies et en les recalculant depuis l'expression (ce qui était fait dans la 2.6 d'après ce que je vois). Cela implique alors que les bindingDependencies ne servent plus à rien (au prix d'un surcout de performance au chargement des variables).

**Comment by ddecrulle** [comment]
On conclu que c'est une erreur de génération ?

**Comment by AnneHuSKa** [comment]
Oui, j'ai creusé et ca ne semble que dans ce cas que les bindingDependencies sont insuffisantes (ShapeFrom et utilisation de LIENS). Je créé issue coté Eno. Merci à @Grafikart et @ddecrulle
