### ISSUE TITLE
Tableaux dynamiques - Roster for Loop - affichage de la question

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#839]
## Describe the bug

Le libellé de la question dont la réponse est un tableau dynamique s'affiche dans le bouton sous le tableau (cf. copies écran) - **le sujet n'est pas ici sur headers ou header**

=> Testé sur storybook 2.7 et 2.6, même souci

## To Reproduce

1. Json disposible ici : https://github.com/InseeFr/Lunatic/files/13173751/json_tabdyn_avecControles.zip
2. Go to page 2

## Expected behavior

Affichage du libellé de la question au dessus du tableau
![image](https://github.com/InseeFr/Lunatic/assets/71011059/a2a82074-020e-4178-b2d2-cc4505ca14e7)

## Screenshots

A tort on a :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/488b3b92-4959-4eeb-9afb-6ecc607148e1)

## Version where the bug appeared

Ca n'a jamais marché (en LunaticV2)

## Browser where the bug was tested

- Firefox
 
## Additional context

https://github.com/InseeFr/Lunatic/issues/409

**Comment by romaintailhurat** [comment]
@Grafikart Jonathan, tu penses pouvoir travailler dessus dans les jours qui viennent ?

**Comment by Grafikart** [comment]
Je l'avais déjà corrigé, je regarde où le commit a atterit

**Comment by Grafikart** [comment]
Dans les json de tests que j'ai le libellé sert à piloter le texte du bouton : 

https://github.com/InseeFr/Lunatic/blob/2.7/src/stories/loop/source-roster.json#L17

Si j'utilise le "label" pour la question, on n'aura alors plus la possibilité de changer le texte de ce bouton. C'est le bon comportement ?

**Comment by AnneHuSKa** [comment]
=> "Ajouter une ligne" pour l'instant
A valoriser avec Pogues ultérieurement

**Comment by Grafikart** [comment]
La MR corrige avec ce comportement 

![image](https://github.com/InseeFr/Lunatic/assets/395137/74954e78-17e0-4372-abb0-9f3835a0ad01)
