### ISSUE TITLE
Overview: manage Sequence in Loop

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#842]
## Feature Description

Actually, sequence inside loop are not shown in overview menu.
For each sequence inside loop, we want to display the sequence's title of the first iteration, and the associated page.

## Use Case

When a user open overview menu

## Proposed Solution

Please see related issue

## Alternatives Considered

No alternative

## Priority

- [ ] Low
- [x] Medium
- [ ] High

## Attachments

If applicable, include any mockups, diagrams, or additional files that help illustrate the feature.

## Related Issues

DramaQueen : https://github.com/InseeFr/Drama-Queen/issues/93

**Comment by laurentC35** [comment]
```
| - I Adresse
| - II Tableau des habitants du logement
|         - Boucle / Sous-séquénce répétées
|                  - SS1 d'Alice
|                  - SS1 de Bob
| - Boucle / Séquence répétée
|         - III Les activités d'Alice
|         - III Les activités de Bob
```

**Comment by laurentC35** [comment]
@QRuhier : créer un questionnaire simple + des datas

On itère dessus pour avoir un overview

**Comment by QRuhier** [comment]
@Grafikart 
questionnaire de test avec un peu tous les cas de boucle (boucle non paginée, boucle sur séquence(s)/ss-séquence(s), itération filtrée) : [questionnaire_842.json](https://github.com/InseeFr/Lunatic/files/14882544/questionnaire_842.json)

La structure est de la forme : 
- I - Séquence 1
	- Votre santé
	- Votre logement
- II - Habitants du logement
	- Composition du logement <= boucle non paginée
- III - Détail des individus
	- Boucle sous-séquence
		- Caractéristiques de $PRENOM$
	- Boucle sous-séquences <= boucle filtrée pour le premier individu
		- Autres caractéristiques de $PRENOM$
		- Encore d'autres caractéristiques de $PRENOM$
- Boucle sur séquences		
	- IV - Belle séquence pour $PRENOM$
		- Belle sous-séquence pour $PRENOM$
		- Autre belle sous-seq
	- V - Autre séquence pour $PRENOM$

Dans l'overview, tant qu'on ne connaît pas le nombre d'itérations pour une boucle, on n'aurait aucun item correspondant.

---
Dans cet exemple, en remplissant comme prénoms Quentin, Luna, Paul, la hierarchie deviendrait : 

- I - Séquence 1
	- Votre santé
	- Votre logement
- II - Habitants du logement
- III - Détail des individus
	- Caractéristiques de Quentin
	- Caractéristiques de Luna
	- Caractéristiques de Paul
	- Autres caractéristiques de Quentin <= filtrée donc non atteignable
	- Encore d'autres caractéristiques de Quentin <= filtrée donc non atteignable
	- Autres caractéristiques de Paul
	- Encore d'autres caractéristiques de Paul
	- Autres caractéristiques de Luna
	- Encore d'autres caractéristiques de Luna
- IV - Belle séquence pour Quentin
	- Belle sous-séquence pour Quentin
	- Autre belle sous-seq
- V - Autre séquence pour Quentin
- IV - Belle séquence pour Luna
	- Belle sous-séquence pour Luna
	- Autre belle sous-seq
- V - Autre séquence pour Luna
- IV - Belle séquence pour Paul
	- Belle sous-séquence pour Paul
	- Autre belle sous-seq
- V - Autre séquence pour Paul

[data_842.json](https://github.com/InseeFr/Lunatic/files/14882547/data_842.json)

---

Pas besoin particulier de savoir qu'un overviewItem fait partie d'une boucle : tous les items d'une boucle sont mis à plat avec les items hors boucle.
Comme pour les items hors boucle, une seq/ss-seq (voire itération complète) filtrée doit être flaguée comme non visible ; non reached si elle est avant le lastReachedPage (si le lastReachedPage est dans l'itération 2 d'une boucle, il est impossible d'aller à l'itération 3)
