### ISSUE TITLE
Affichage des modalités - multiplicité ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#855]
## Describe the bug

Questionnaire généré avec EnoJava.
Dans une question hors boucle de type CheckBox, les modalités de réponse décrites sont Oui - Non  mais les modalités affichées sont :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/1788ba6a-f041-48c3-ad68-4a2f29aefc0c)

- [ ] I tested it on the storybook, which leads me to believe that it's a lunatic bug.
=> j'ai reproduit une fois le bug en Lunatic mais plus ensuite..

## To Reproduce

1. With the survey available here  
[EDT_Queen_2.7.zip](https://github.com/InseeFr/Lunatic/files/14008331/EDT_Queen_2.7.zip)
2. Aller page 4, saisir 4, 
3. Aller page 5, saisir 4 prénoms
4. Passer toutes les pages suivantes
5. See error page 26

![image](https://github.com/InseeFr/Lunatic/assets/71011059/5a5fd33b-0041-4cce-9d1e-c9fefc627d93)

## Expected behavior

Modalité affichée une unique fois, et systématiquement.

## Screenshots

cf. infra

## Version where the bug appeared

Queen : 1.1.22 | Lunatic : 2.7.13 

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

## Additional context

J'avais déjà vu ce souci il y a qq semaines puis il avait disparu. Je recherche à quel moment.

**Comment by AnneHuSKa** [comment]
En attente correction questionnaire par concepteur

**Comment by AnneHuSKa** [comment]
Bug reproduit sur un petit questionnaire en PJ. Vu avec @BulotF  (qui va commenter l'issue)
[bug_CodeDouble.zip](https://github.com/InseeFr/Lunatic/files/14027243/bug_CodeDouble.zip)

![image](https://github.com/InseeFr/Lunatic/assets/71011059/196edf53-a727-4967-a984-2636132d9c46)
pour la variable hors boucle (numéro 5) dont les modalités de réponse sont celles de la question 3 de la boucle 

Pour reproduire, mettre 3 individus.

**Comment by BulotF** [comment]
Complément d'analyse : 
Le bug a été identifié dans Queen qui s'appuie sur Lunatic 2.7, mais n'est pas dans Stromae qui s'appuie sur Lunatic 2.6

Le questionnaire contient : 
- une boucle
PUIS
- des questions Radio ou Liste déroulante hors boucle dont les Options/Label étaient déjà présents pour une question de la boucle

Ex : 
- OuiOuiOuiOui
- NonNonNonNon
- Peut-êtrePeut-êtrePeut-êtrePeut-être

Par contre VOui et No sont conservés tels quels : les libellés doivent être exactement identiques.

Les listes de modalités n'ont pas à être exactement identiques : Si la boucle non contient que Oui et Non, on pourra avoir : 
- OuiOuiOuiOui
- NonNonNonNon
- Peut-être
