### ISSUE TITLE
Selecting a missing in "loop" component doesn't set the button "active"

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#861]
## Describe the bug

In "loop" component, if you select a missing response (don't know / refusal) , the value is saved but the button does not look "checked".
On other components it seems ok.

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

1. can use in storybook questionnaire "tictel", with missing
2. Go to page 2, answer "Oui"
3. Go to page 6 (whatever your answer on page 5)
4. Check a missing response

## Expected behavior

As for every component, selecting a missing response (don't know / refusal) should set the button "active"

![image](https://github.com/InseeFr/Lunatic/assets/99256289/cd517db2-f2d3-4262-83f1-557f6e7d80cd)

## Screenshots

current behavior on loop component :
![image](https://github.com/InseeFr/Lunatic/assets/99256289/1e2bcea1-5445-4365-a8aa-54d53bce552f)

## Version where the bug appeared

Observed on lunatic 2.7.13, but don't know when it appeared

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by Grafikart** [comment]
It doesn't happen on the v3, do you need a fix for the 2.7 too ?

**Comment by QRuhier** [comment]
Indeed it works on 3.0.0
I let @AnneHuSKa answer, knowing that we shouldn't use 2.7 anymore on our apps in a month

**Comment by AnneHuSKa** [comment]
Juste 3.0
