### ISSUE TITLE
Valorisation de certains filtres non fonctionnelle?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#864]
## Description 

Dans le json en PJ, si les 4 variables de boucles liées COMBIENA, COMBIENB, COMBIENC et COMBIEND sont vides, on ne devrait pas afficher la question 12 (filtrée sur ces 4 variables).

- Testé dans storybook et idem

## Reproduire le bug

1. Charger le questionnaire 
[DQissue109.zip](https://github.com/InseeFr/Drama-Queen/files/14100270/DQissue109.zip)

2. Commencer la saisie (2 individus)
3. Peu importe sexe, date de naissance
4. Ne pas remplir les variable COMBIENA à COMBIEND (saisir des 0 ou des NSP)
5. Constater que la question 12 est affichée à tort, voire contient des "," si on saisit des NSP (cf. infra)
 
![image](https://github.com/InseeFr/Drama-Queen/assets/71011059/d2b2780a-c164-4138-8c8e-dc3d94664d5b)

## Attendu 

Afficher la question 12 uniquement si la condition du filtre est remplie

## Testé en 
-  Firefox

**Comment by AnneHuSKa** [comment]
Complément vu avec @QRuhier : 
- dans Lunatic, le souci apparait si on met des missing. En revanche, tout fonctionne comme attendu si on "passe" les questions .
- répondre par des 0 partout : la question est affichée, à tort mais vide 
- saisir 2 individus, ne faire que des missing : la variable QUESTIONFI est affichée à tort et contient une , (la valeur collected de la variable est initialisée à : Array [ null, null ] alors que la variable n'est pas dans une boucle)
- on peut saisir un montant et elle se transforme en scalaire

**Comment by Grafikart** [comment]
J'ai un peu investigué et le calcul "(nvl(SUMA,0) > 0 or nvl(SUMB,0) > 0 or nvl(SUMC,0) > 0 or nvl(SUMD,0) > 0)" est fait à certaines itérations (lors des cleaning). Le système part donc du principe que c'est une expression d'itération et stocke les résultat pour chaque itération.

Quand on lui demande la valeur de cette même expression en dehors d'une itération il renvoie `[false, false, false]` ce qui constitue une valeur positive en JavaScript. 

## Solutions : 

- Créer une variable calculée qui aura un shape from, ce qui permettra de savoir la forme attendue
- Modiifer lunatic pour forcer un booléen dans le conditionFilter.

**Comment by romaintailhurat** [comment]
@Grafikart  Les deux solutions que tu listes sont nécessaires ou il s'agit d'une alternative ?

**Comment by AnneHuSKa** [comment]
@Grafikart @laurentC35 @nsenave : complément !
J'ai tenté de créer un json tout simple et n'ai plus eu le souci. En comparant le json simple et le json initial, j'ai constaté que la présence du pairwise modifie les resizing. Je joins donc 2 json : un simple avec liens et un simple sans liens. On a testé avec @QRuhier : dans celui sans liens, toute saisie semble être ok (qu'on choisisse des missing ou des vraies valeurs), dans celles avec Liens on a le bug d'affichage à tort.

![image](https://github.com/InseeFr/Lunatic/assets/71011059/b0e98144-a738-4b96-8c79-0622e38f844f)
[DQissue109_sansLien.zip](https://github.com/InseeFr/Lunatic/files/14138409/DQissue109_sansLien.zip)
[DQissue109_avecLien.zip](https://github.com/InseeFr/Lunatic/files/14138410/DQissue109_avecLien.zip)

**Comment by nsenave** [comment]
Au niveau génération c'est lié à ceci: https://github.com/InseeFr/Eno/issues/733#issuecomment-1772395598 (voir la discussion jusqu'en bas)

cf. la description actuelle du resizing dans l'input json Lunatic qui est bancale...

@Grafikart @laurentC35 de mon côté je ne saurais pas dire précisément les implications dans Lunatic

**Comment by romaintailhurat** [comment]
Nous venons de tester avec Queen : 1.1.26 | Lunatic : 2.7.15.

Le problème est toujours là mais valide le [symptôme décrit par Anne](https://github.com/InseeFr/Lunatic/issues/864#issuecomment-1923463164) à savoir que le même questionnaire sans les liens deux à deux fonctionne correctement mais présente le bug dans une version qui inclut les liens deux à deux.

**Comment by romaintailhurat** [comment]
@Grafikart @ddecrulle @QRuhier Vous voyez lequel d'entre vous peut travailler sur le sujet ?

**Comment by laurentC35** [comment]
D'après @nsenave, le problème viendrait d'un pb de modélisation `resising` et/ou `shapeFrom` ?

**Comment by Grafikart** [comment]
Si je prend le premier questionnaire je n'arrive plus à produire le bug sur le storybook :(
A travers une autre issue j'ai détecté un problème sur le pairwise (https://github.com/InseeFr/Lunatic/pull/870) donc à voir si cela résoud aussi cette issue.

**Comment by AnneHuSKa** [comment]
@Grafikart c'est fort possible car j'ai creusé et en fait quand on a un questionnaire avec des liens deux à deux, la première "saisie" fonctionne (les questions s'affichent ou se masquent conformément aux filtres) mais quand on modifie les données de variables impliquées dans le filtre, ca ne marche pas. Ton sujet sur le pairwise (https://github.com/InseeFr/Lunatic/pull/870) impacte plus ou moins toutes les variables des boucles c'est ca ?

**Comment by AnneHuSKa** [comment]
@Grafikart @ddecrulle un complément d'explication avec une petite vidéo. [test_bdf.zip](https://github.com/InseeFr/Lunatic/files/14179887/test_bdf.zip)
[video1503080259.zip](https://github.com/InseeFr/Lunatic/files/14179904/video1503080259.zip)

**Comment by AnneHuSKa** [comment]
merci @ddecrulle et merci @Grafikart
