### ISSUE TITLE
data outside loop are lost on init

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#867]
## Describe the bug
When you start a questionnaire with initial data, the data for collected variables outside loop are lost, we see a empty object instead `{}`

## To Reproduce
With behaviour "Paste" in storybook

## Expected behavior
We want to keep initial data

## Version where the bug appeared
The last one : `2.7.13`

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge

**Comment by QRuhier** [comment]
problem coming from [there](https://github.com/InseeFr/Lunatic/blob/2.7/src/utils/variables.ts) :  collected variable outside of loop only respects the first "if" condition so updated data is never returned (returning undefined)

Another question : why is there a difference between L20 (prioritize collected value) and L26 (prioritize forced value) ?

**Comment by laurentC35** [comment]
For your question, I think it's a mistake.

Actually "FORCED" value are not use.
This is a future feature (management mode).

I suggest to allways display COLLECTED value
