### ISSUE TITLE
TCM - calcul de variables inter niveaux

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#873]
## Describe the bug

Un nouveau sujet "mise à jour" de données. Dans le cas présent, la variable T_MER1E par exemple, qui utilise une calculée de niveau individu (qui utilise des liens et se calcule bien T_NBPARL) et une collectée de niveau individu (T_SPAR1) ne semble pas se mettre à jour quand T_NBPARL = "0".
Formule :  `if T_NBPARL = "0" then "2" else ( if nvl(T_SPAR1,"1") = "2" then "1" else "2")`

Ce qui semble étrange en saisissant 3 individus dans le storybook : le nb de null de chaque occurrence ?

```json
    "T_SPAR1": {
        "COLLECTED": [
            "1",
            [
                null,
                null,
                null
            ],
            [
                null,
                null
            ]
        ],
        "EDITED": [],
        "INPUTED": [],
        "FORCED": [],
        "PREVIOUS": []
    }
```

[data_json.zip](https://github.com/InseeFr/Lunatic/files/14208612/data_json.zip)

-  I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce
 [TCM_extrait.zip](https://github.com/InseeFr/Lunatic/files/14208528/TCM_extrait.zip)

**Comment by AnneHuSKa** [comment]
@romaintailhurat lrhzu528 en prod

**Comment by AnneHuSKa** [comment]
Video le retour : 


https://github.com/InseeFr/Lunatic/assets/81740200/98c14b06-a8a5-42a9-a1f7-46aea3f1fbba


Test en Lunatic : 
- Cannot interpret expression : "MERE dans le logement : " || T_MER1E  Error: Cannot interpret expression "if T_NBPARL = "0" then "2" else ( if nvl(T_SPAR1,"1") = "2" then "1" else "2" )" with bindings {"T_NBPARL":"0","T_SPAR1":[null,null,null],"T_NHAB":3}, error : incompatible type, required 'DATASET' but found 'STRING' for then operand
T_SPAR1 collectée dans une boucle liée, NBPARL calculée avec des données de boucles, valable pour chaque occurrence de boucle.
- encore qq tentatives d'affichage de variables array : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/c3b38f17-af04-4b2a-a29c-4877e584991c)
- T_SPAR1 collectée dans la console : 
```json
"T_SPAR1": {
      "COLLECTED": [
        [
          null,
          null,
          null
        ],
        "2",
        [
          null,
          null
        ]
      ],
      "EDITED": [],
      "INPUTED": [],
      "FORCED": [],
      "PREVIOUS": []
    },
```
- json testable 
[JsonVideo.zip](https://github.com/InseeFr/Lunatic/files/14223721/JsonVideo.zip)

**Comment by romaintailhurat** [comment]
Correction à venir de @Grafikart

**Comment by romaintailhurat** [comment]
@AnneHuSKa j'ai vérifié avec ton questionnaire (`lrhzu528`), on a le bon fonctionnement avec cette nouvelle version de Lunatic. 😄
