### ISSUE TITLE
Lenteur questionnaire SRCV

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#887]
## Describe the bug
Lenteur du questionnaire pour les questions 2 (nb habitants) et 3 (collecte des prénoms
=> I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce
1. With the survey available here/uploaded  
[SRCV_2602.zip](https://github.com/InseeFr/Lunatic/files/14402306/SRCV_2602.zip)

2. Go to page 2
3. Click on "3"
4. Wait...

## Expected behavior
Questionnaire moins lent.

## Version where the bug appeared
2.7 mais 2.6 semble un peu lente également (StromaeV2)

## Browser where the bug was tested
-  Firefox

## Additional context
A priori la suppression du bloc cleaning résoud le pb mais n'y-a-t-il pas aussi un souci de syntaxe ? Beaucoup de filtres sont créés, avec des données de boucles notamment

**Comment by romaintailhurat** [comment]
According to @laurentC35 @ddecrulle ➡️ a refacto is in progress, better perfs will be available in two sprints (6 weeks)

**Comment by Grafikart** [comment]
Si je réactive le cache (qui créé des problèmes de variable calculé) on a des lenteurs moins conséquentes, mais ça reste lent. 

Certaines expressions sont éxécutées un très grand nombre de fois, j'ai fait un tableau des éxécutions lorsque je tape une valeur dans le champs : 

![image](https://github.com/InseeFr/Lunatic/assets/395137/102f181e-49f0-45a4-b85e-a72504692e82)


Créer des variables calculées pour ces expressions permettrait la mise en cache du résultat (le cache ne s'active que pour les variables avec un shapeFrom) et devrait améliorer significativement les performances.

## Détail 

Graph d'éxécution 

![image](https://github.com/InseeFr/Lunatic/assets/395137/5bed951e-666e-414c-a62a-457bc78c1c89)

Graph déxécution si le cache est forcé (on pourrrait s'approcher de ce résultat avec des variables intermédiaires)

![image](https://github.com/InseeFr/Lunatic/assets/395137/62af1cc1-9a98-499c-8c00-42d06144e18a)

**Comment by AnneHuSKa** [comment]
@Grafikart : on peut proposer au concepteur de créer des var calculées pour la première expression mais les autres sont déjà des expressions calculées - exemple  T_C_ENF_M = sum(^T_C_ENF_I) et c'est T_C_ENF_M qui est appelé dans d'autres expressions donc je ne vois pas comment réduire ?
``
		{
			"variableType": "CALCULATED",
			"bindingDependencies": [
				"T_C_ENF_I",
				"T_NHAB"
			],
			"expression": {
				"type": "VTL",
				"value": "sum(T_C_ENF_I)"
			},
			"name": "T_C_ENF_M"
		},
``

**Comment by AnneHuSKa** [comment]
@Grafikart : on a testé avec la création pour la première expression mais on a la même lenteur 
[SRCV_2902.zip](https://github.com/InseeFr/Lunatic/files/14461545/SRCV_2902.zip)

**Comment by AnneHuSKa** [comment]
J'ai eu un autre cas : un questionnaire sur lequel j'ai ajouté un filtre sur REPONDANT = "1" (REPONDANT = "1" se base sur des données de boucles et on pose ensuite des questions à certains des individus de la boucle). Je passe de qq secondes à plus de 20 secondes pour la question sur nb habitants.
[EDT_filtreRepondant.zip](https://github.com/InseeFr/Lunatic/files/14463215/EDT_filtreRepondant.zip)

**Comment by romaintailhurat** [comment]
Un filtre Pogues sur N questions == N filtres Lunatic ?

Il faut un système de cache pour le calcul des filtres ? 🤔 😄

**Comment by Grafikart** [comment]
Voila ce que je vois de mon côté (questionnaire avec filtre) : 
![image](https://github.com/InseeFr/Lunatic/assets/395137/63552eff-fc2f-45b9-bb93-7c44e955bdd7)

Il y a certaines choses qui m'étonne comme par exemple les binding dependencies de KISH_MIN

```json
      "bindingDependencies": [
        "SCORE_KISH_INT",
        "T_AN",
        "T_DATENAIS"
      ],
      "expression": {
        "type": "VTL",
        "value": "min(SCORE_KISH_INT)"
      },
```

Si j'en crois l'expression la valeur ne devrait changer que lorsque SCORE_KISH_INT change.
Aussi, il n'y a pas de shapeFrom sur ces variables là du coup pas de cache d'actif :( 

Par exemple si je met 

```json
      "shapeFrom": "HEUREDEB",
```

Cela active le cache (pour des variables de premier niveau)

**Comment by AnneHuSKa** [comment]
Pas de ShapeFrom <=> variable de niveau questionnaire @Grafikart (pour l'exemple d'avant, "KISH_MIN" est de niveau questionnaire donc pas de shapeFrom et dans l'exemple de départ, T_C_ENF_M est de niveau questionnaire aussi )

**Comment by Grafikart** [comment]
D'après ce qu'on s'est dit au dernier daily, j'ai réactivé le cache dans cette MR #902 .
Cela améliore grandement le temps mais on continue de perdre du temps sur l'éxécution du cleaning qui a beaucoup d'expressions qui ne sont pas des variables.
