### ISSUE TITLE
Pairwise links UX enhancement

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#892]
## Feature Description

Several UX enhancement proposal have been made for the Pairwise links component.

➡️ [See this document](https://www.figma.com/proto/OBXNYpNe9ShsXcXmRtSXEX/Liens-2-%C3%A0-2?page-id=0%3A1&type=design&node-id=4-4357&viewport=1235%2C1351%2C1&t=9qe5uKvSnpdyt18N-1&scaling=scale-down&starting-point-node-id=4%3A4357&show-proto-sidebar=1)

## Use Case

Enhance this component for a better UI.

## Additional Context

Option A is the contender for a quick enhancement, stories will be developed to test the different sub options.

Design work must be conducted for the more costly or strong option, we are targeting specially the E.

## Priority

- Medium

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/pull/910
Dans storybook 3.0

**Comment by AnneHuSKa** [comment]
ok dans le storybook
