### ISSUE TITLE
Error message triggering on RosterForLoop

### ISSUE THREAD

**Issue by jdirand** [InseeFr/Lunatic#894]
## Describe the bug

- If I press next without filling the first component, an error message appears even if if I haven't specified any control. 
- The component(s) on the following row(s) move to the right for some reason

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce
Copy/Paste the JSON below in Storybook to reproduce the bug

[Json_avecNull.json](https://github.com/InseeFr/Lunatic/files/14423636/Json_avecNull.json)
[Json_avecIII.json](https://github.com/InseeFr/Lunatic/files/14423637/Json_avecIII.json)

## Expected behavior

The error message should not appear unless I have added a specific control.
The components on the following rows should not move to the right. 

## Screenshots

![image](https://github.com/InseeFr/Lunatic/assets/5951368/29838d3d-c279-4469-a119-25ac7b51daf4)

## Version where the bug appeared

2.7

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by AnneHuSKa** [comment]
Pour le Json_avecIII.json, on s'attend à ce que le message ne se déclenche que si la cellule vaut III.
Mais pour la première ligne, on a assez un message d'erreur tant qu'on n'a rien saisi :
![image](https://github.com/InseeFr/Lunatic/assets/71011059/8ddf0e01-7188-45f1-b6d4-89b84af101eb)
Data : {
   "COLLECTED": {
    "NATS": {
      "PREVIOUS": [
        null
      ],
      "COLLECTED": [
        null,
        "III",
        "ESSAI"
      ],
      "FORCED": [
        null
      ],
      "EDITED": [
        null
      ],
      "INPUTED": [
        null
      ]
    }
  }
}
En revanche, une fois qu'on a rempli la première cellule, puis qu'on la vide, on n'a plus le message - ce qui est l'attendu 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/2cd1a6fe-0114-4b32-ae9c-7b9bd06ea734)
ou
![image](https://github.com/InseeFr/Lunatic/assets/71011059/8d5e1596-2ad3-4575-8147-d9f70eb5267f)

**Comment by Grafikart** [comment]
C'est un cas un peu particulier car en fait quand on ajoute une nouvelle ligne la ligne s'affiche mais n'est pas intégrée dans les données (2 champs affichés, mais 1 seul élément dans les données). La validation ne se déclenche donc pas car il n'y a pas de données à valider. 

Une solution pour remédier à ce problème serait de prendre tous les composants (avec une réponse) dans la ligne qui est ajouté et de mettre un "null" par défaut. Mais cette approche devient complexe car il faut détecter les composants de la ligne pour savoir comment mettre ce null (par exemple si on a un checkboxGroup la logique est plus complexe)

**Comment by AnneHuSKa** [comment]
Pas généré dans la filière
