### ISSUE TITLE
Can't display `GLOBAL_ITERATION_INDEX` in a declaration

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#896]
## Describe the bug

I can't display the value of `GLOBAL_ITERATION_INDEX` in a string, for example using a declaration:

```json
{
	"declarationType": "HELP",
	"id": "lrotnbqz",
	"label": {
		"type": "VTL|MD",
		"value": "\"Dans l'itération \" || cast(GLOBAL_ITERATION_INDEX, string)\""
	},
	"position": "AFTER_QUESTION_TEXT"
}
```

When i'm checking using the storybook, i can see the following error in the browser console:

```
Cannot interpret expression : "Dans l'itération " || cast(GLOBAL_ITERATION_INDEX, string)" Error: Cannot interpret expression ""Dans l'itération " || cast(GLOBAL_ITERATION_INDEX, string)"" with bindings {"GLOBAL_ITERATION_INDEX":2}, error : Error: Type errors:
	 LexerNoViableAltException
```

🤔 The value of the variable is present in this error message (`2` in this case). 🤔 

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

1. With the questionnaire attached (see below)
2. In the first question ("N"), enter a number, for example 2
3. In the next page, you'll see the VTL formula instead of the expected string; you can also check the error message in the console.

[lunatic-896.zip](https://github.com/InseeFr/Lunatic/files/14435644/lunatic-896.zip)

## Expected behavior

The variable is available for being cast as a string.

## Version where the bug appeared

The 2.7.something of the current storybook.

## Browser where the bug was tested

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by AnneHuSKa** [comment]
If you add "" after the cast(), there is no problem
```
"id": "lu8jxwyk",
"page": "3",
"label": {
"type": "VTL|MD",
"value": "\"➡ 3. \" || \"Prénom (avec un espace à la fin, après GLOBAL etc) de l'individu numéro \" || cast(GLOBAL_ITERATION_INDEX, string) || \"\""
},
"mandatory": false,
"maxLength": 249
```

**Comment by ddecrulle** [comment]
Thanks Anne for the fix, on my opinion it's not a Lunatic Issue but VTL execution issue (so maybe Trevas JS ? ).
