### ISSUE TITLE
Do not inject style in the library

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#901]
## Feature Description

Currently, the default styles provided by Lunatic are applied universally across components. However, there's a need to customize these styles or refrain from using the default styling altogether.

## Use Case

Lunatic styles, such as those defined in [index.scss](https://github.com/InseeFr/Lunatic/blob/2.7/src/components/index.scss), are automatically applied to components, including dynamically imported styles such as [Input.scss](https://github.com/InseeFr/Lunatic/blob/2.7/src/components/Input/Input.scss).

The current workaround involves wrapping components with `<LunaticComponents>` to override the default styles, which adds the `className="lunatic lunatic-component"` attribute.

Additionally, some styles are not scoped properly and are applied globally, as seen in [this example](https://github.com/InseeFr/Lunatic/blob/2.7/src/components/index.scss#L2), which is inadvertently imported by [variableStatus](https://github.com/InseeFr/Lunatic/blob/6f762a69de309765772c25a69604250f9fe5e5e4/src/components/shared/VariableStatus/VariableStatus.scss#L2).

This not only affects the styling but also impacts the build bundle size due to dynamically imported styles in the client application.

![Screenshot](https://github.com/InseeFr/Lunatic/assets/81740200/dc5577c8-12e4-4c36-9fdd-fcd7e2207f96)

## Proposed Solution

To address this issue, it's proposed that the orchestrator handles the import of Lunatic styles, allowing for more flexibility and customization.

## Alternatives Considered

As a short-term workaround, scoping all styles could be considered to mitigate the global styling issue.

## Priority

- [ ] Low
- [ ] Medium
- [x] High

**Comment by Grafikart** [comment]
Fixed by a4cc8dcd8c8cf958d7d1686463750f06084c5165
