### ISSUE TITLE
Suggester enhancement over alphanumeric sort

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#908]
## Feature Description

We are currently [benchmarking ](https://inseefr.github.io/Lunatic/tmp/iframe.html?args=&id=behaviour-search--default&viewMode=story) Minisearch as an alternative to IndexDB. So far so good, but i identified a possible enhancement with the `L_COMMUNEPASSEE-1-2-0`.

When typing `paris`, the Minisearch results are:

```
Paris 10e
Paris 11e
...
```

But we would expect:

```
Paris 1er
Paris 2e
...
```
## Priority

- [x] Low
- [ ] Medium
- [ ] High

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/1166
