### ISSUE TITLE
RosterForLoop - Support simple labels as component

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#911]
## Feature Description

Pogues will provide a way to inject external values into a RosterForLoop (aka dynamic table) columns, see https://github.com/InseeFr/Pogues/issues/745. Lunatic must enable that by supporting a "Label" as a RosterForLoop component.

## Use Case

Describe the specific use case or scenario where this feature would be beneficial.

## Proposed Solution

Simple Tables support the use of labels, see [this story](https://github.com/InseeFr/Lunatic/blob/2.7/src/stories/table/source-roster.json#L22). 

Injecting such a label object in a RosterForLoop has no effect.

```json
"components": [
        {
          "label": {
            "value": "Simple label",
            "type": "VTL|MD"
          }
        }
]
```

We may then have a proper text / label / typography component, and thus having this kind of structure:

```json
"components": [
        {
          "componentType": "Label",
          "value": "\"A VTL expression\" || EXTERNAL_VAR"
          "type": "VTL|MD"
       }
]
```

## Priority

Needed for some business surveys questionnaire.

- [ ] Low
- [x] Medium
- [ ] High

## Related Issues

- https://github.com/InseeFr/Pogues/issues/745
- https://github.com/InseeFr/Eno/issues/932

**Comment by Grafikart** [comment]
We introduced a new component type for this kind of use case

```json
{
	"componentType": "Text",
	"label": { "value": "\"Individu \" || cast(GLOBAL_ITERATION_INDEX, string)", "type": "VTL" }
},
```
