### ISSUE TITLE
Bug for a computed variable in a loop

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Lunatic#917]
## Describe the bug

A calculated variable on a questionnaire is having a bad structure. 

The computed variable `T_MENAGE_PRINC` from the TCM has in a problematic use case this form:

```json
"T_MENAGE_PRINC": [
      1,
      0,
      [
        0,
        0
      ]
    ],
```

That is, instead of having `n` scalars in its array (here `n = 3`, because the loop have 3 iterations), we have the last index being an array of 2.

- [x] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

In order to reproduce, i attach here two questionnaires:

- the first one `srcv-buggy.json` has the bug, 
- the other `srcv-placebo-ok.json` don't.

To reproduce the issue:

1. With `srcv-buggy.json` on the storybook 2.7
2. Choose a number, for example `3` for this question
![image](https://github.com/InseeFr/Lunatic/assets/1663283/6aa9c03d-70f6-4923-a8e5-6e8458cecb39)
4. In the following question add a surname for each inhabitants
5. You can skip answers until the birthdate that should make the individuals adult (use `2000` for example) 
![image](https://github.com/InseeFr/Lunatic/assets/1663283/6fa3567d-1b13-4bbf-96b2-5587ffeeab92)
6. Skip everything until the pairwise question in which everyone is a housemate ("colocataire")
![image](https://github.com/InseeFr/Lunatic/assets/1663283/f7e610d9-c473-42cf-8e13-f70212be7b4d)
7. Skip to the "other house" question and answer "No" for everyone
![image](https://github.com/InseeFr/Lunatic/assets/1663283/281300b6-1db1-4015-9412-2ab2cc2737ca)
8. At last, we arrived to the "test" Sequence which display various variables including `T_MENAGE_PRINC` and we can see the last one is not working (because of the structure highlighted above) 
![image](https://github.com/InseeFr/Lunatic/assets/1663283/2d679ca7-6557-462d-a1ee-4b6713e43715)

## Source questionnaires

[srcv-bug.zip](https://github.com/InseeFr/Lunatic/files/14801387/srcv-bug.zip)

**Comment by Grafikart** [comment]
@romaintailhurat 
Quel est la différence entre les 2 json ?
Que représente la variable T_MENAGE_PRINC ?

**Comment by romaintailhurat** [comment]
La variable `T_MENAGE_PRINC` est une variable de boucle sur chaque habitant du logement pour déterminer s'il fait partie du ménage principal, sa valeur est 1 ou 0. Le code VTL:

```
if ($T_TYPE_MEN_LOG$ = 1 or $T_TYPE_MEN_LOG$ = 2 or $T_TYPE_MEN_LOG$ = 3 or $T_TYPE_MEN_LOG$ = 5) then 1
else if ($T_TYPE_MEN_LOG$ = 4) then (
    if ($PRENOM$ = $PRENOMREF$) then 1
    else 0)
else (
    if $T_NB_MEN_FINAL$ = 1 then 1
    else (
        if (nvl($T_MP$,"1") = "1") then 1
        else 0))
```

**Comment by romaintailhurat** [comment]
Le premier JSON (`srcv-buggy.json`) correspond au questionnaire qui porte le bug, sa construction dans Pogues est la suivante:

![image](https://github.com/InseeFr/Lunatic/assets/1663283/a3a30730-21e4-46ad-b34d-604388d9f3b2)

En vert, le module qui contient les variables calculées (dont `T_MENAGE_PRINC`). En rouge, la séquence dans laquelle on affiche les variables (et dans laquelle on constate le bug).

Les deux modules qui suivnet  `TCM_THL_DET_PROXY` ainsi que la séquence _test_ sont dans des boucles liées à la boucle des prénoms (issue de `TCM_THL_DET_PROXY`).

Le second questionnaire (dans lequel on ne constate pas le problème) a la structure suivante - elle reprend l'idée du questionnaire problématique en le simplifiant:

![image](https://github.com/InseeFr/Lunatic/assets/1663283/503f4ea4-6893-4824-8b6b-0b8fbbdc9552)

**Comment by romaintailhurat** [comment]
Pour information: dans les deux cas, on utilise le module `TCM_THL_DET_PROXY` qui inclut le _Pairwise_.
