### ISSUE TITLE
Tooltips - How to improve them ?

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#957]
## Feature Description

How to improve the tooltip ?

## Use Case

For instance, today, you can have a tooltip like this one : 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/bce19b7c-cc40-4e76-abef-697bb029775f)

## Proposed Solution

https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/infobulle
something like this "infobulle au clic" ?
something shorter ? in a smaller "box" ?

## Priority

- [ ] Low
- [X] Medium
- [ ] High

**Comment by ddecrulle** [comment]
We need to add the possibility to customize Tooltip as other components

**Comment by AnneHuSKa** [comment]
@ddecrulle @Grafikart : Is it expensive ? Even if we try to avoid tooltips, they are very "used" by Pogues' users
