### ISSUE TITLE
Suggester

### ISSUE THREAD

**Issue by ddecrulle** [InseeFr/Lunatic#960]
## Describe the bug

Suggester is not working as expected since the arbitrary option has been added.

- [ ] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

### With classic suggester

When we clear the suggester after selecting an option without losing focus and we write some text, searches are well executed but not displayed because onBlur has been called by [onChange](https://github.com/InseeFr/Lunatic/blob/4220c69dd3101c3dded980df470dfdab0ab21109/src/components/Suggester/Suggester.tsx#L97) and the local isFocused state in useSuggestion is false so only [selected option](https://github.com/InseeFr/Lunatic/blob/4220c69dd3101c3dded980df470dfdab0ab21109/src/components/Suggester/useSuggestions.ts#L80) are displayed

https://github.com/InseeFr/Lunatic/assets/81740200/e630835d-a2cb-462d-9899-2145adffa738

### with arbitrary option : 

- We can't select the arbitrary option as expected

https://github.com/InseeFr/Lunatic/assets/81740200/f091ff24-43df-40ab-b2bf-3fa19ca3ae1c

- When we have a classic option selected and we add some text, if we click on the input, extra text is deleted

https://github.com/InseeFr/Lunatic/assets/81740200/e420092d-3a02-4eee-b30f-929c0d67386e

**Comment by Grafikart** [comment]
Le coeur du problème résulte de cet évènement onBlur car dans un scénario classique :

- J'ai une valeur dans le champs (A)
- Je tape une recherche
- Je blur
- La valeur entrée avant la recherche est remise dans le champs (A)

Maintenant le souci c'est que souvent quand on clique sur une suggestion, on déclenche aussi le "blur" du champs ce qui déclenche le onBlur.

- J'ai une valeur dans le champs (A)
- Je tape une recherche
- Je sélectionne une valeur (ce qui déclenche un onBlur et onChange)
- La valeur entrée avant la recherche est remise dans le champs (A)
- La valeur de la recherche (donc A) est utilisée à la place de ce qui avait été entré.
