### ISSUE TITLE
Ajouter un état "Current" aux variables

### ISSUE THREAD

**Issue by AgatheLM** [InseeFr/Lunatic#978]
- Ajouter aux état Lunatic : _Collected_ = Brute, _Edited_ = Modifiée, _Forced_ = Redressée  l'état Courrant _current_ 

- Faire en sorte que les variables calculées  s'appuient sur cet état Current
Mettre en place un "état calculé" qui est initialisé par ce qui vient de Genesis, et lorsqu'on met a jour l'état édité ça met à jour cet état la
=> _current_ (?) si c'est "retour/vidage" à la valeur brute il remet l'état brut dans _current_.
       => _current_ peut soit prendre la valeur de la variable soit l’état principal
     - Le moteur lunatic s’appuiera toujours sur cet état

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/1003#issuecomment-2122238258
