### ISSUE TITLE
suggesters : missing response not checked + hasPageResponse returning false

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#994]
## Describe the bug

On a suggester component, when selecting a missing response, the value is well saved, but : 
- button remains unchecked
- hasPageResponse returns false

- [ ] I tested it on the storybook, which leads me to believe that it's a lunatic bug.

## To Reproduce

1. With the survey available here/uploaded in issue
2. Go to '...'
3. Click on '....'
4. See error ...

## Version where the bug appeared

lunatic 3.0.0-rc.34

## Browser where the bug was tested

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] Other (please specify): ******\_\_\_******

**Comment by Grafikart** [comment]
Could you provide a JSON to reproduce this error ?
