### ISSUE TITLE
Add label & lunaticModelVersion to LunaticSource type

### ISSUE THREAD

**Issue by QRuhier** [InseeFr/Lunatic#999]
Queen is using LunaticSource type for questionnaire.
It needs label value of the questionnaire, and lunaticModelVersion, that are in the lunatic-json

Currently, the "label" and "lunaticModelVersion" variables are not included in LunaticSource type.
It would be easier to have it included (even if optional), otherwise Queen must overload LunaticSource

**Comment by ddecrulle** [comment]
#1000
